### ISSUE TITLE
IOCharger IOCH10-22T measureands problem

### ISSUE THREAD

**Issue by stefan73** [lbbrhzn/ocpp#1124]
I have a IOCharger IOCH10-22T. These are sold in Germany as Entratek Power Dot Fix. This OCPP implementation basically works and I am now using 0.52. I can set the charge current for 3 phase charging from 6 to max and start/stop charging.
The problem are the measureands, which seem to get lost more and more with each update of this implementation. E.g. with 0.51 Current import, export and offered were available. With 0.52 those are now gone too. Now with 0.52 thre is only Energy Meter Start, Energy Session, Time Session, Transaction Id, Voltage left.
While charging only Voltage updates every 60s. The other value update every 900s. Restarting home assistant changes the measureands that I condigured in the charger web-interface. If I configure MeterValuesSampledData to report Current.Import,Energy.Active.Import.Register,Voltage,Current.Offered , this entry switches back to voltage only after the HA restart. The values for MeterValuesAlignedData remain. So what I see in the charger WebIF seems consistent with the observed reporting intervals.
If I change the measureands in the charger WebIF, the values update faster. 
I fail to make measureands persistent in the HA/Charger combination. And I fail to win back the values that got reported in prior versions.
Questions: Charger Firmware bug? - Can I somehow mitigate the situation?
Goal: Up to date (60s) values at least for Current Import and Energy Meter.

Here is a log after restarting HA:
<details>
2024-03-29 18:14:22.730 WARNING (SyncWorker_1) [homeassistant.loader] We found a custom integration pyscript which has not been tested by Home Assistant. This component might cause stability problems, be sure to disable it if you experience issues with Home Assistant
2024-03-29 18:14:22.732 WARNING (SyncWorker_1) [homeassistant.loader] We found a custom integration ocpp which has not been tested by Home Assistant. This component might cause stability problems, be sure to disable it if you experience issues with Home Assistant
2024-03-29 18:14:22.733 WARNING (SyncWorker_1) [homeassistant.loader] We found a custom integration hacs which has not been tested by Home Assistant. This component might cause stability problems, be sure to disable it if you experience issues with Home Assistant
2024-03-29 18:14:22.734 WARNING (SyncWorker_1) [homeassistant.loader] We found a custom integration solcast_solar which has not been tested by Home Assistant. This component might cause stability problems, be sure to disable it if you experience issues with Home Assistant
2024-03-29 18:14:32.026 WARNING (MainThread) [homeassistant.helpers.frame] Detected that custom integration 'hacs' accesses hass.components.frontend. This is deprecated and will stop working in Home Assistant 2024.9, it should be updated to import functions used from frontend directly at custom_components/hacs/frontend.py, line 68: hass.components.frontend.async_register_built_in_panel(, please create a bug report at https://github.com/hacs/integration/issues
2024-03-29 18:14:32.541 WARNING (MainThread) [homeassistant.components.sensor] Entity sensor.solcast_pv_forecast_prognose_heute (<class 'custom_components.solcast_solar.sensor.SolcastSensor'>) is using state class 'measurement' which is impossible considering device class ('energy') it is using; expected None or one of 'total', 'total_increasing'; Please update your configuration if your entity is manually configured, otherwise create a bug report at https://github.com/oziee/ha-solcast-solar/issues
2024-03-29 18:14:34.800 ERROR (MainThread) [homeassistant.helpers.event] Error while processing template: Template<template=({% set voltage = states('sensor.wallbox_voltage') | float %} {% set current = states('sensor.wallbox_current_import') | float %}
{{ (voltage * current) | round(1, default=0) }}) renders=2>
Traceback (most recent call last):
File "/usr/src/homeassistant/homeassistant/helpers/template.py", line 2037, in forgiving_float_filter
return float(value)
^^^^^^^^^^^^
ValueError: could not convert string to float: 'unavailable'
During handling of the above exception, another exception occurred:
Traceback (most recent call last):
File "/usr/src/homeassistant/homeassistant/helpers/template.py", line 573, in async_render
render_result = _render_with_context(self.template, compiled, **kwargs)
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "/usr/src/homeassistant/homeassistant/helpers/template.py", line 2364, in _render_with_context
return template.render(**kwargs)
^^^^^^^^^^^^^^^^^^^^^^^^^
File "/usr/local/lib/python3.12/site-packages/jinja2/environment.py", line 1301, in render
self.environment.handle_exception()
File "/usr/local/lib/python3.12/site-packages/jinja2/environment.py", line 936, in handle_exception
raise rewrite_traceback_stack(source=source)
File "<template>", line 1, in top-level template code
File "/usr/src/homeassistant/homeassistant/helpers/template.py", line 2040, in forgiving_float_filter
raise_no_default("float", value)
File "/usr/src/homeassistant/homeassistant/helpers/template.py", line 1668, in raise_no_default
raise ValueError(
ValueError: Template error: float got invalid input 'unavailable' when rendering template '{% set voltage = states('sensor.wallbox_voltage') | float %} {% set current = states('sensor.wallbox_current_import') | float %}
{{ (voltage * current) | round(1, default=0) }}' but no default was specified
The above exception was the direct cause of the following exception:
Traceback (most recent call last):
File "/usr/src/homeassistant/homeassistant/helpers/template.py", line 699, in async_render_to_info
render_info._result = self.async_render(
^^^^^^^^^^^^^^^^^^
File "/usr/src/homeassistant/homeassistant/helpers/template.py", line 575, in async_render
raise TemplateError(err) from err
homeassistant.exceptions.TemplateError: ValueError: Template error: float got invalid input 'unavailable' when rendering template '{% set voltage = states('sensor.wallbox_voltage') | float %} {% set current = states('sensor.wallbox_current_import') | float %}
{{ (voltage * current) | round(1, default=0) }}' but no default was specified
2024-03-29 18:14:34.810 ERROR (MainThread) [homeassistant.components.template.template_entity] TemplateError('ValueError: Template error: float got invalid input 'unavailable' when rendering template '{% set voltage = states('sensor.wallbox_voltage') | float %} {% set current = states('sensor.wallbox_current_import') | float %}
{{ (voltage * current) | round(1, default=0) }}' but no default was specified') while processing template 'Template<template=({% set voltage = states('sensor.wallbox_voltage') | float %} {% set current = states('sensor.wallbox_current_import') | float %}
{{ (voltage * current) | round(1, default=0) }}) renders=4>' for attribute '_attr_native_value' in entity 'sensor.wallbox_power'
2024-03-29 18:14:34.933 INFO (MainThread) [custom_components.pyscript.file.pv_excess_control.pv_excess_control] [switch.wallbox_charge_control (Prio 2)] Trigger Method started.
2024-03-29 18:14:34.934 INFO (MainThread) [custom_components.pyscript.file.pv_excess_control.pv_excess_control] [switch.wallbox_charge_control (Prio 2)] Registered appliance.
2024-03-29 18:14:34.934 INFO (MainThread) [custom_components.pyscript.file.pv_excess_control.pv_excess_control] Dict: {'automation.pv_ueberschuss_optimierer': {'instance': <custom_components.pyscript.eval.PvExcessControl object at 0x7fd5a898f080>, 'priority': 2}}
2024-03-29 18:14:34.935 WARNING (MainThread) [homeassistant.components.automation.pv_ueberschuss_optimierer] PV Ueberschuss Optimierer: Already running
2024-03-29 18:14:34.964 INFO (MainThread) [ocpp] 38CC7A28A780440BA6965171059494EF: receive message [2,"17117324741608752","Heartbeat",{}]
2024-03-29 18:14:34.977 INFO (MainThread) [ocpp] 38CC7A28A780440BA6965171059494EF: send [3,"17117324741608752",{"currentTime":"2024-03-29T17:14:34Z"}]
2024-03-29 18:14:35.368 WARNING (MainThread) [homeassistant.helpers.entity_component] Forced update failed. Entity sensor.wallbox_energy_reactive_import_interval not found.
2024-03-29 18:14:35.369 WARNING (MainThread) [homeassistant.helpers.entity_component] Forced update failed. Entity sensor.wallbox_energy_reactive_import_register not found.
2024-03-29 18:14:35.369 WARNING (MainThread) [homeassistant.helpers.entity_component] Forced update failed. Entity sensor.wallbox_power_reactive_export not found.
2024-03-29 18:14:35.369 WARNING (MainThread) [homeassistant.helpers.entity_component] Forced update failed. Entity sensor.wallbox_rpm not found.
2024-03-29 18:14:35.370 WARNING (MainThread) [homeassistant.helpers.entity_component] Forced update failed. Entity sensor.wallbox_frequency not found.
2024-03-29 18:14:35.370 WARNING (MainThread) [homeassistant.helpers.entity_component] Forced update failed. Entity sensor.wallbox_power_reactive_import not found.
2024-03-29 18:14:35.370 WARNING (MainThread) [homeassistant.helpers.entity_component] Forced update failed. Entity sensor.wallbox_current_export not found.
2024-03-29 18:14:35.370 WARNING (MainThread) [homeassistant.helpers.entity_component] Forced update failed. Entity sensor.wallbox_energy_reactive_export_register not found.
2024-03-29 18:14:35.370 WARNING (MainThread) [homeassistant.helpers.entity_component] Forced update failed. Entity sensor.wallbox_current_import not found.
2024-03-29 18:14:35.370 WARNING (MainThread) [homeassistant.helpers.entity_component] Forced update failed. Entity sensor.wallbox_energy_active_import_interval not found.
2024-03-29 18:14:35.371 WARNING (MainThread) [homeassistant.helpers.entity_component] Forced update failed. Entity sensor.wallbox_energy_active_export_register not found.
2024-03-29 18:14:35.371 WARNING (MainThread) [homeassistant.helpers.entity_component] Forced update failed. Entity sensor.wallbox_current_offered not found.
2024-03-29 18:14:35.371 WARNING (MainThread) [homeassistant.helpers.entity_component] Forced update failed. Entity sensor.wallbox_energy_active_export_interval not found.
2024-03-29 18:14:35.371 WARNING (MainThread) [homeassistant.helpers.entity_component] Forced update failed. Entity sensor.wallbox_power_active_export not found.
2024-03-29 18:14:35.371 WARNING (MainThread) [homeassistant.helpers.entity_component] Forced update failed. Entity sensor.wallbox_power_offered not found.
2024-03-29 18:14:35.372 WARNING (MainThread) [homeassistant.helpers.entity_component] Forced update failed. Entity sensor.wallbox_power_active_import not found.
2024-03-29 18:14:35.372 WARNING (MainThread) [homeassistant.helpers.entity_component] Forced update failed. Entity sensor.wallbox_energy_reactive_export_interval not found.
2024-03-29 18:14:35.372 WARNING (MainThread) [homeassistant.helpers.entity_component] Forced update failed. Entity sensor.wallbox_soc not found.
2024-03-29 18:14:35.372 WARNING (MainThread) [homeassistant.helpers.entity_component] Forced update failed. Entity sensor.wallbox_temperature not found.
2024-03-29 18:14:35.372 WARNING (MainThread) [homeassistant.helpers.entity_component] Forced update failed. Entity sensor.wallbox_energy_active_import_register not found.
2024-03-29 18:14:35.372 WARNING (MainThread) [homeassistant.helpers.entity_component] Forced update failed. Entity sensor.wallbox_power_factor not found.
2024-03-29 18:14:35.692 INFO (MainThread) [custom_components.pyscript.file.pv_excess_control.pv_excess_control] [switch.steckdose (Prio 1)] Trigger Method started.
2024-03-29 18:14:35.692 INFO (MainThread) [custom_components.pyscript.file.pv_excess_control.pv_excess_control] [switch.steckdose (Prio 1)] Registered appliance.
2024-03-29 18:14:35.693 INFO (MainThread) [custom_components.pyscript.file.pv_excess_control.pv_excess_control] Dict: {'automation.pv_ueberschuss_optimierer': {'instance': <custom_components.pyscript.eval.PvExcessControl object at 0x7fd5a898f080>, 'priority': 2}, 'automation.pv_ueberschuss_heizung': {'instance': <custom_components.pyscript.eval.PvExcessControl object at 0x7fd5a724cf20>, 'priority': 1}}
2024-03-29 18:14:36.786 INFO (MainThread) [ocpp] 38CC7A28A780440BA6965171059494EF: send [2,"8c9c3bef-f481-4cd9-9007-6aa4769df51f","GetConfiguration",{"key":["SupportedFeatureProfiles"]}]
2024-03-29 18:14:36.960 INFO (MainThread) [ocpp] 38CC7A28A780440BA6965171059494EF: receive message [3,"8c9c3bef-f481-4cd9-9007-6aa4769df51f",{"configurationKey":[{"key":"SupportedFeatureProfiles","readonly":true,"value":"Core,FirmwareManagement,LocalAuthListManagement,Reservation,SmartCharging,RemoteTrigger"}]}]
2024-03-29 18:14:36.969 INFO (MainThread) [ocpp] 38CC7A28A780440BA6965171059494EF: send [2,"69b41b2e-da09-4b73-88e3-284f2a4e91f0","GetConfiguration",{"key":["NumberOfConnectors"]}]
2024-03-29 18:14:37.179 INFO (MainThread) [ocpp] 38CC7A28A780440BA6965171059494EF: receive message [3,"69b41b2e-da09-4b73-88e3-284f2a4e91f0",{"configurationKey":[{"key":"NumberOfConnectors","readonly":true,"value":"1"}]}]
2024-03-29 18:14:37.180 INFO (MainThread) [ocpp] 38CC7A28A780440BA6965171059494EF: send [2,"091bc2b9-2964-4e11-8788-b535cb7cd674","GetConfiguration",{"key":["HeartbeatInterval"]}]
2024-03-29 18:14:37.280 INFO (MainThread) [ocpp] 38CC7A28A780440BA6965171059494EF: receive message [3,"091bc2b9-2964-4e11-8788-b535cb7cd674",{"configurationKey":[{"key":"HeartbeatInterval","readonly":false,"value":"3600"}]}]
2024-03-29 18:14:37.290 INFO (MainThread) [ocpp] 38CC7A28A780440BA6965171059494EF: send [2,"3ad5d5b6-64b1-44b3-b944-86b77871e769","ChangeConfiguration",{"key":"MeterValuesSampledData","value":"Voltage"}]
2024-03-29 18:14:37.401 INFO (MainThread) [ocpp] 38CC7A28A780440BA6965171059494EF: receive message [3,"3ad5d5b6-64b1-44b3-b944-86b77871e769",{"status":"Accepted"}]
2024-03-29 18:14:37.417 INFO (MainThread) [ocpp] 38CC7A28A780440BA6965171059494EF: send [2,"e82d520a-0d07-4b25-9eb3-1ad4bafbe67d","GetConfiguration",{"key":["MeterValuesSampledData"]}]
2024-03-29 18:14:37.478 INFO (MainThread) [ocpp] 38CC7A28A780440BA6965171059494EF: receive message [3,"e82d520a-0d07-4b25-9eb3-1ad4bafbe67d",{"configurationKey":[{"key":"MeterValuesSampledData","readonly":false,"value":"Voltage"}]}]
2024-03-29 18:14:37.480 INFO (MainThread) [ocpp] 38CC7A28A780440BA6965171059494EF: send [2,"7d1e1727-fd7a-4b05-8bdc-a9bf9893b703","GetConfiguration",{"key":["MeterValueSampleInterval"]}]
2024-03-29 18:14:37.641 INFO (MainThread) [ocpp] 38CC7A28A780440BA6965171059494EF: receive message [3,"7d1e1727-fd7a-4b05-8bdc-a9bf9893b703",{"configurationKey":[{"key":"MeterValueSampleInterval","readonly":false,"value":"60"}]}]
2024-03-29 18:14:37.656 INFO (MainThread) [ocpp] 38CC7A28A780440BA6965171059494EF: send [2,"0cf796fb-dc92-4f8f-8819-eacea6e5db39","GetConfiguration",{"key":["ClockAlignedDataInterval"]}]
2024-03-29 18:14:37.682 INFO (MainThread) [ocpp] 38CC7A28A780440BA6965171059494EF: receive message [3,"0cf796fb-dc92-4f8f-8819-eacea6e5db39",{"configurationKey":[{"key":"ClockAlignedDataInterval","readonly":false,"value":"900"}]}]
2024-03-29 18:14:37.684 INFO (MainThread) [ocpp] 38CC7A28A780440BA6965171059494EF: send [2,"39614ed8-718f-4f75-bf5d-bbaf60424514","GetConfiguration",{"key":["WebSocketPingInterval"]}]
2024-03-29 18:14:37.782 INFO (MainThread) [ocpp] 38CC7A28A780440BA6965171059494EF: receive message [3,"39614ed8-718f-4f75-bf5d-bbaf60424514",{"configurationKey":[{"key":"WebSocketPingInterval","readonly":false,"value":"60"}]}]
2024-03-29 18:14:37.784 INFO (MainThread) [ocpp] 38CC7A28A780440BA6965171059494EF: send [2,"6ae1ec64-e675-43cb-910e-052908e87129","ChangeAvailability",{"connectorId":0,"type":"Operative"}]
2024-03-29 18:14:37.881 INFO (MainThread) [ocpp] 38CC7A28A780440BA6965171059494EF: receive message [3,"6ae1ec64-e675-43cb-910e-052908e87129",{"status":"Accepted"}]
2024-03-29 18:14:37.884 INFO (MainThread) [ocpp] 38CC7A28A780440BA6965171059494EF: send [2,"94e3f99e-8d2b-4233-b10c-327aae860eaa","TriggerMessage",{"requestedMessage":"BootNotification"}]
2024-03-29 18:14:37.980 INFO (MainThread) [ocpp] 38CC7A28A780440BA6965171059494EF: receive message [3,"94e3f99e-8d2b-4233-b10c-327aae860eaa",{"status":"Accepted"}]
2024-03-29 18:14:37.983 INFO (MainThread) [ocpp] 38CC7A28A780440BA6965171059494EF: send [2,"551f1ade-c856-40a1-8ab9-87407eb20049","TriggerMessage",{"requestedMessage":"StatusNotification","connectorId":0}]
2024-03-29 18:14:38.081 INFO (MainThread) [ocpp] 38CC7A28A780440BA6965171059494EF: receive message [2,"17117324771611952","BootNotification",{"chargeBoxSerialNumber":"20122401-20210911","chargePointModel":"IOCAH10-22T","chargePointSerialNumber":"A11215012047","chargePointVendor":"IoCharger","firmwareVersion":"22121701-21111301-21111301"}]
2024-03-29 18:14:38.084 INFO (MainThread) [ocpp] 38CC7A28A780440BA6965171059494EF: send [3,"17117324771611952",{"currentTime":"2024-03-29T17:14:38Z","interval":3600,"status":"Accepted"}]
2024-03-29 18:14:38.089 WARNING (MainThread) [homeassistant.helpers.entity_component] Forced update failed. Entity sensor.wallbox_energy_reactive_import_interval not found.
2024-03-29 18:14:38.090 WARNING (MainThread) [homeassistant.helpers.entity_component] Forced update failed. Entity sensor.wallbox_energy_reactive_import_register not found.
2024-03-29 18:14:38.090 WARNING (MainThread) [homeassistant.helpers.entity_component] Forced update failed. Entity sensor.wallbox_power_reactive_export not found.
2024-03-29 18:14:38.090 WARNING (MainThread) [homeassistant.helpers.entity_component] Forced update failed. Entity sensor.wallbox_rpm not found.
2024-03-29 18:14:38.091 WARNING (MainThread) [homeassistant.helpers.entity_component] Forced update failed. Entity sensor.wallbox_frequency not found.
2024-03-29 18:14:38.091 WARNING (MainThread) [homeassistant.helpers.entity_component] Forced update failed. Entity sensor.wallbox_power_reactive_import not found.
2024-03-29 18:14:38.091 WARNING (MainThread) [homeassistant.helpers.entity_component] Forced update failed. Entity sensor.wallbox_current_export not found.
2024-03-29 18:14:38.091 WARNING (MainThread) [homeassistant.helpers.entity_component] Forced update failed. Entity sensor.wallbox_energy_reactive_export_register not found.
2024-03-29 18:14:38.091 WARNING (MainThread) [homeassistant.helpers.entity_component] Forced update failed. Entity sensor.wallbox_current_import not found.
2024-03-29 18:14:38.091 WARNING (MainThread) [homeassistant.helpers.entity_component] Forced update failed. Entity sensor.wallbox_energy_active_import_interval not found.
2024-03-29 18:14:38.091 WARNING (MainThread) [homeassistant.helpers.entity_component] Forced update failed. Entity sensor.wallbox_energy_active_export_register not found.
2024-03-29 18:14:38.092 WARNING (MainThread) [homeassistant.helpers.entity_component] Forced update failed. Entity sensor.wallbox_current_offered not found.
2024-03-29 18:14:38.092 WARNING (MainThread) [homeassistant.helpers.entity_component] Forced update failed. Entity sensor.wallbox_energy_active_export_interval not found.
2024-03-29 18:14:38.092 WARNING (MainThread) [homeassistant.helpers.entity_component] Forced update failed. Entity sensor.wallbox_power_active_export not found.
2024-03-29 18:14:38.092 WARNING (MainThread) [homeassistant.helpers.entity_component] Forced update failed. Entity sensor.wallbox_power_offered not found.
2024-03-29 18:14:38.092 WARNING (MainThread) [homeassistant.helpers.entity_component] Forced update failed. Entity sensor.wallbox_power_active_import not found.
2024-03-29 18:14:38.092 WARNING (MainThread) [homeassistant.helpers.entity_component] Forced update failed. Entity sensor.wallbox_energy_reactive_export_interval not found.
2024-03-29 18:14:38.092 WARNING (MainThread) [homeassistant.helpers.entity_component] Forced update failed. Entity sensor.wallbox_soc not found.
2024-03-29 18:14:38.093 WARNING (MainThread) [homeassistant.helpers.entity_component] Forced update failed. Entity sensor.wallbox_temperature not found.
2024-03-29 18:14:38.093 WARNING (MainThread) [homeassistant.helpers.entity_component] Forced update failed. Entity sensor.wallbox_energy_active_import_register not found.
2024-03-29 18:14:38.093 WARNING (MainThread) [homeassistant.helpers.entity_component] Forced update failed. Entity sensor.wallbox_power_factor not found.
2024-03-29 18:14:38.201 INFO (MainThread) [ocpp] 38CC7A28A780440BA6965171059494EF: receive message [3,"551f1ade-c856-40a1-8ab9-87407eb20049",{"status":"Rejected"}]
2024-03-29 18:14:38.202 WARNING (MainThread) [custom_components.ocpp] Failed with response: Rejected
2024-03-29 18:14:38.202 INFO (MainThread) [ocpp] 38CC7A28A780440BA6965171059494EF: send [2,"8334f460-4e78-4e2c-bcb5-f30b71ff58c0","TriggerMessage",{"requestedMessage":"StatusNotification","connectorId":1}]
2024-03-29 18:14:38.405 INFO (MainThread) [ocpp] 38CC7A28A780440BA6965171059494EF: receive message [2,"17117324771612278","StatusNotification",{"connectorId":0,"errorCode":"NoError","status":"Available","timestamp":"2024-03-29T17:14:37Z"}]
2024-03-29 18:14:38.408 INFO (MainThread) [ocpp] 38CC7A28A780440BA6965171059494EF: send [3,"17117324771612278",{}]
2024-03-29 18:14:38.411 WARNING (MainThread) [homeassistant.helpers.entity_component] Forced update failed. Entity sensor.wallbox_energy_reactive_import_interval not found.
2024-03-29 18:14:38.412 WARNING (MainThread) [homeassistant.helpers.entity_component] Forced update failed. Entity sensor.wallbox_energy_reactive_import_register not found.
2024-03-29 18:14:38.412 WARNING (MainThread) [homeassistant.helpers.entity_component] Forced update failed. Entity sensor.wallbox_power_reactive_export not found.
2024-03-29 18:14:38.412 WARNING (MainThread) [homeassistant.helpers.entity_component] Forced update failed. Entity sensor.wallbox_rpm not found.
2024-03-29 18:14:38.412 WARNING (MainThread) [homeassistant.helpers.entity_component] Forced update failed. Entity sensor.wallbox_frequency not found.
2024-03-29 18:14:38.413 WARNING (MainThread) [homeassistant.helpers.entity_component] Forced update failed. Entity sensor.wallbox_power_reactive_import not found.
2024-03-29 18:14:38.413 WARNING (MainThread) [homeassistant.helpers.entity_component] Forced update failed. Entity sensor.wallbox_current_export not found.
2024-03-29 18:14:38.413 WARNING (MainThread) [homeassistant.helpers.entity_component] Forced update failed. Entity sensor.wallbox_energy_reactive_export_register not found.
2024-03-29 18:14:38.413 WARNING (MainThread) [homeassistant.helpers.entity_component] Forced update failed. Entity sensor.wallbox_current_import not found.
2024-03-29 18:14:38.413 WARNING (MainThread) [homeassistant.helpers.entity_component] Forced update failed. Entity sensor.wallbox_energy_active_import_interval not found.
2024-03-29 18:14:38.413 WARNING (MainThread) [homeassistant.helpers.entity_component] Forced update failed. Entity sensor.wallbox_energy_active_export_register not found.
2024-03-29 18:14:38.414 WARNING (MainThread) [homeassistant.helpers.entity_component] Forced update failed. Entity sensor.wallbox_current_offered not found.
2024-03-29 18:14:38.414 WARNING (MainThread) [homeassistant.helpers.entity_component] Forced update failed. Entity sensor.wallbox_energy_active_export_interval not found.
2024-03-29 18:14:38.414 WARNING (MainThread) [homeassistant.helpers.entity_component] Forced update failed. Entity sensor.wallbox_power_active_export not found.
2024-03-29 18:14:38.414 WARNING (MainThread) [homeassistant.helpers.entity_component] Forced update failed. Entity sensor.wallbox_power_offered not found.
2024-03-29 18:14:38.414 WARNING (MainThread) [homeassistant.helpers.entity_component] Forced update failed. Entity sensor.wallbox_power_active_import not found.
2024-03-29 18:14:38.414 WARNING (MainThread) [homeassistant.helpers.entity_component] Forced update failed. Entity sensor.wallbox_energy_reactive_export_interval not found.
2024-03-29 18:14:38.414 WARNING (MainThread) [homeassistant.helpers.entity_component] Forced update failed. Entity sensor.wallbox_soc not found.
2024-03-29 18:14:38.415 WARNING (MainThread) [homeassistant.helpers.entity_component] Forced update failed. Entity sensor.wallbox_temperature not found.
2024-03-29 18:14:38.415 WARNING (MainThread) [homeassistant.helpers.entity_component] Forced update failed. Entity sensor.wallbox_energy_active_import_register not found.
2024-03-29 18:14:38.415 WARNING (MainThread) [homeassistant.helpers.entity_component] Forced update failed. Entity sensor.wallbox_power_factor not found.
2024-03-29 18:14:38.496 INFO (MainThread) [ocpp] 38CC7A28A780440BA6965171059494EF: receive message [3,"8334f460-4e78-4e2c-bcb5-f30b71ff58c0",{"status":"Rejected"}]
2024-03-29 18:14:38.497 WARNING (MainThread) [custom_components.ocpp] Failed with response: Rejected
2024-03-29 18:14:38.711 INFO (MainThread) [ocpp] 38CC7A28A780440BA6965171059494EF: receive message [2,"17117324771612579","StatusNotification",{"connectorId":1,"errorCode":"NoError","status":"Preparing","timestamp":"2024-03-29T17:14:37Z"}]
2024-03-29 18:14:38.712 INFO (MainThread) [ocpp] 38CC7A28A780440BA6965171059494EF: send [3,"17117324771612579",{}]
2024-03-29 18:14:38.714 WARNING (MainThread) [homeassistant.helpers.entity_component] Forced update failed. Entity sensor.wallbox_energy_reactive_import_interval not found.
2024-03-29 18:14:38.715 WARNING (MainThread) [homeassistant.helpers.entity_component] Forced update failed. Entity sensor.wallbox_energy_reactive_import_register not found.
2024-03-29 18:14:38.715 WARNING (MainThread) [homeassistant.helpers.entity_component] Forced update failed. Entity sensor.wallbox_power_reactive_export not found.
2024-03-29 18:14:38.715 WARNING (MainThread) [homeassistant.helpers.entity_component] Forced update failed. Entity sensor.wallbox_rpm not found.
2024-03-29 18:14:38.715 WARNING (MainThread) [homeassistant.helpers.entity_component] Forced update failed. Entity sensor.wallbox_frequency not found.
2024-03-29 18:14:38.716 WARNING (MainThread) [homeassistant.helpers.entity_component] Forced update failed. Entity sensor.wallbox_power_reactive_import not found.
2024-03-29 18:14:38.716 WARNING (MainThread) [homeassistant.helpers.entity_component] Forced update failed. Entity sensor.wallbox_current_export not found.
2024-03-29 18:14:38.716 WARNING (MainThread) [homeassistant.helpers.entity_component] Forced update failed. Entity sensor.wallbox_energy_reactive_export_register not found.
2024-03-29 18:14:38.716 WARNING (MainThread) [homeassistant.helpers.entity_component] Forced update failed. Entity sensor.wallbox_current_import not found.
2024-03-29 18:14:38.716 WARNING (MainThread) [homeassistant.helpers.entity_component] Forced update failed. Entity sensor.wallbox_energy_active_import_interval not found.
2024-03-29 18:14:38.716 WARNING (MainThread) [homeassistant.helpers.entity_component] Forced update failed. Entity sensor.wallbox_energy_active_export_register not found.
2024-03-29 18:14:38.717 WARNING (MainThread) [homeassistant.helpers.entity_component] Forced update failed. Entity sensor.wallbox_current_offered not found.
2024-03-29 18:14:38.717 WARNING (MainThread) [homeassistant.helpers.entity_component] Forced update failed. Entity sensor.wallbox_energy_active_export_interval not found.
2024-03-29 18:14:38.717 WARNING (MainThread) [homeassistant.helpers.entity_component] Forced update failed. Entity sensor.wallbox_power_active_export not found.
2024-03-29 18:14:38.717 WARNING (MainThread) [homeassistant.helpers.entity_component] Forced update failed. Entity sensor.wallbox_power_offered not found.
2024-03-29 18:14:38.717 WARNING (MainThread) [homeassistant.helpers.entity_component] Forced update failed. Entity sensor.wallbox_power_active_import not found.
2024-03-29 18:14:38.717 WARNING (MainThread) [homeassistant.helpers.entity_component] Forced update failed. Entity sensor.wallbox_energy_reactive_export_interval not found.
2024-03-29 18:14:38.717 WARNING (MainThread) [homeassistant.helpers.entity_component] Forced update failed. Entity sensor.wallbox_soc not found.
2024-03-29 18:14:38.718 WARNING (MainThread) [homeassistant.helpers.entity_component] Forced update failed. Entity sensor.wallbox_temperature not found.
2024-03-29 18:14:38.718 WARNING (MainThread) [homeassistant.helpers.entity_component] Forced update failed. Entity sensor.wallbox_energy_active_import_register not found.
2024-03-29 18:14:38.718 WARNING (MainThread) [homeassistant.helpers.entity_component] Forced update failed. Entity sensor.wallbox_power_factor not found.
</details>

**Comment by stefan73** [comment]
Reinstalling does unfortunately not help.
The problem is not the reporting interval and how it is set up. The 60 seconds reporting interval during charging works - but only for voltage.

For clarification:
The charger supports the following values: Current.Import, Energy.Active.Import.Register ,Voltage, Current.Offered, Temperature, SoC. I can set those values for MeterValuesSampledData or MeterValuesAlignedData. 
Problem #1 When setting up values as MeterValuesSampledData in the charger firmware, the reporting inverval for the selected values increases to 60 seconds. BUT upon restarting HA, the MeterValuesSampledData setting in the charger is reset to voltage only.
Problem #2: With 0.52 of this code, the integration reports Current.Import, Current.Offered, Temperature and Energy.Active.Import.Register as not available. Those values were available with 0.51.

So the problems are: Loss of sensor / measureands with 0.52 and reset of MeterValuesSampledData entries with HA starting.

**Comment by drc38** [comment]
See https://github.com/lbbrhzn/ocpp/issues/1096#issue-2159922663

The log should test each measurand for support by the charger.

**Comment by drc38** [comment]
If you can no longer select measurands on setup try replacing line 464 in `api.py` with:
`all_measurands = MEASURANDS`

You will need to add  `MEASURANDS` to the import line as well.

**Comment by stefan73** [comment]
Solution https://github.com/lbbrhzn/ocpp/issues/1150
