### ISSUE TITLE
Unexpected exception importing ocpp

### ISSUE THREAD

**Issue by gnsa14** [lbbrhzn/ocpp#1184]
OCPP does not load on HA boot

Just updated HA to version Core 2024.5.5

 - Device:          PC
 - OS:                Generic x86-64
 - Core              2024.5.5
 - Supervisor    2024.05.1
 - Operating System    12.2
 - Frontend      20240501.1
 - OCPP            v0.5.2

Logger: homeassistant.loader
Source: loader.py:1046
First occurred: 12:47:48 PM (2 occurrences)
Last logged: 12:47:49 PM

Unexpected exception importing component custom_components.ocpp
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/loader.py", line 1046, in _get_component
    ComponentProtocol, importlib.import_module(self.pkg_path)
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/util/loop.py", line 144, in protected_loop_func
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/importlib/__init__.py", line 90, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<frozen importlib._bootstrap>", line 1387, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1360, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1331, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 935, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/config/custom_components/ocpp/__init__.py", line 13, in <module>
    from .api import CentralSystem
  File "/config/custom_components/ocpp/api.py", line 52, in <module>
    from .const import (
  File "/config/custom_components/ocpp/const.py", line 121, in <module>
    UnitOfMeasure.hertz: ha.UnitOfFrequency.HERTZ,
    ^^^^^^^^^^^^^^^^^^^
AttributeError: type object 'UnitOfMeasure' has no attribute 'hertz'

**Comment by gnsa14** [comment]
Sorry, i didn't see updates for OCPP to 0.5.6
I installed this, and issues were resolved.
