### ISSUE TITLE
Growatt Thor 22AS - Keeps rebooting

### ISSUE THREAD

**Issue by Plawasan** [lbbrhzn/ocpp#1272]
## Version of the custom_component
v0.5.8

## Configuration

"Skip OCPP schema validation" is enabled but doesn't seem to make any difference, same with "Force Smart Charging feature profile"

## Describe the bug
The charger connects and seems to provide some basic information however it keeps reconnecting/rebooting
![image](https://github.com/user-attachments/assets/b9348131-51c4-4df0-927c-9345dab2df5b)

![image](https://github.com/user-attachments/assets/b68b750e-270e-4586-914e-cd40dff9479e)

When connected to Steve, the charger provides data as expected:
![image](https://github.com/user-attachments/assets/c1a2321b-6534-443e-9fdd-1a84eab929c2)

## Debug log

```text
logger:
  default: info
  logs:
    custom_components.ocpp: debug
    websockets.server: debug


Logger: custom_components.ocpp
Source: custom_components/ocpp/api.py:1023
integration: Open Charge Point Protocol (OCPP) ([documentation](https://github.com/lbbrhzn/ocpp/blob/main/README.md), [issues](https://github.com/lbbrhzn/ocpp/issues))
First occurred: 20:05:13 (1 occurrences)
Last logged: 20:05:13

Unexpected exception in connection to 'XGJ0000321510194': 'list index out of range'
Traceback (most recent call last):
  File "/config/custom_components/ocpp/api.py", line 1023, in run
    await asyncio.gather(*self.tasks)
  File "/config/custom_components/ocpp/api.py", line 459, in post_connect
    await self.get_supported_features()
  File "/config/custom_components/ocpp/api.py", line 575, in get_supported_features
    feature_list = (resp.configuration_key[0][om.value.value]).split(",")
                    ~~~~~~~~~~~~~~~~~~~~~~^^^
IndexError: list index out of range

```

**Comment by Plawasan** [comment]
I've copied over the updated version, the reboots are no longer an issue however I still cannot control the charger.

For example when I try to reduce the charging current, I get a `Failed to perform the action number/set_value. list index out of range` error in the GUI and this in logs:

```
Logger: homeassistant.components.websocket_api.http.connection
Source: components/websocket_api/commands.py:241
integration: Home Assistant WebSocket API (documentation, issues)
First occurred: 11:57:48 (4 occurrences)
Last logged: 16:50:11

[140655833854688] Unexpected exception
[140655313004160] Unexpected exception
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/components/websocket_api/commands.py", line 241, in handle_call_service
    response = await hass.services.async_call(
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/core.py", line 2763, in async_call
    response_data = await coro
                    ^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/core.py", line 2806, in _execute_service
    return await target(service_call)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/helpers/service.py", line 999, in entity_service_call
    single_response = await _handle_entity_call(
                      ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/helpers/service.py", line 1071, in _handle_entity_call
    result = await task
             ^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/components/number/__init__.py", line 120, in async_set_value
    await entity.async_set_native_value(native_value)
  File "/config/custom_components/ocpp/number.py", line 129, in async_set_native_value
    resp = await self.central_system.set_max_charge_rate_amps(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/ocpp/api.py", line 298, in set_max_charge_rate_amps
    return await self.charge_points[cp_id].set_charge_rate(limit_amps=value)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/ocpp/api.py", line 674, in set_charge_rate
    resp = await self.get_configuration(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/ocpp/api.py", line 895, in get_configuration
    value = resp.configuration_key[0][om.value.value]
            ~~~~~~~~~~~~~~~~~~~~~~^^^
IndexError: list index out of range
```

I also tried to enable Charge control (which turns off again), however this also turns off Availability (which can't then be turned back on due to this error):

Ocpp integration
Warning: Set availability failed with response Scheduled

(I had to reconfigure the charger back to Steve to turn Availability on again)

Apologies for the mixing multiple issues in the same post, I'm happy to open a separate issue for the individual problems if that's preferred

Thanks!
