### ISSUE TITLE
Smappee EV Wall Business warning (and non-functional)

### ISSUE THREAD

**Issue by clousberg** [lbbrhzn/ocpp#1384]
Trying to get the OCPP connection working for my Smappee EV Wall Business, I ran into some logging which might be the reason that the OCPP integration is not working.

The OCPP connection between the Smappee cloud is setup (arranged a DNS-entry at Smappee to my HA installation) and OCPP is receiving data from Smappee.

Enitity "switch.charger_availability" is working, and also some diagnostics like ping/ping/serial/stop reason/vendor/version (and some more).
Main issue is that the sensors are in some kind of stale state and never change.
![image](https://github.com/user-attachments/assets/ed0f374c-d387-4c30-ac09-065b251cc8b7)

I would like to receive sensor data to be able to calculate correct costs per session.

Currently running on the latest HA (2024.10.4) and OCPP (v0.5.14)

Last info:

Debug log is showing the following (see 2024-11-02 19:58:29.256)

```
2024-11-02 19:58:25.257 WARNING (MainThread) [homeassistant.components.climate] Entity None (<class 'custom_components.tesla_custom.climate.TeslaCarClimate'>) implements HVACMode(s): heat_cool, off and therefore implicitly supports the turn_on/turn_off methods without setting the proper ClimateEntityFeature. Please create a bug report at https://github.com/alandtse/tesla/issues
2024-11-02 19:58:28.988 DEBUG (MainThread) [websockets.server] = connection is CONNECTING
2024-11-02 19:58:28.992 DEBUG (MainThread) [websockets.server] < GET /SMP_6120001832 HTTP/1.1
2024-11-02 19:58:28.992 DEBUG (MainThread) [websockets.server] < Upgrade: websocket
2024-11-02 19:58:28.992 DEBUG (MainThread) [websockets.server] < Connection: upgrade
2024-11-02 19:58:28.992 DEBUG (MainThread) [websockets.server] < Host: {MANUAL HIDDEN}
2024-11-02 19:58:28.992 DEBUG (MainThread) [websockets.server] < X-Forwarded-Scheme: https
2024-11-02 19:58:28.992 DEBUG (MainThread) [websockets.server] < X-Forwarded-Proto: https
2024-11-02 19:58:28.992 DEBUG (MainThread) [websockets.server] < X-Forwarded-For: {IP SMAPPEE(AWS) MANUAL HIDDEN}
2024-11-02 19:58:28.992 DEBUG (MainThread) [websockets.server] < X-Real-IP: {IP SMAPPEE(AWS) MANUAL HIDDEN}
2024-11-02 19:58:28.992 DEBUG (MainThread) [websockets.server] < Sec-WebSocket-Protocol: ocpp1.6
2024-11-02 19:58:28.992 DEBUG (MainThread) [websockets.server] < sec-websocket-key: DblwbCUBVxWdcfdOSYlYUg==
2024-11-02 19:58:28.992 DEBUG (MainThread) [websockets.server] < sec-websocket-version: 13
2024-11-02 19:58:28.993 DEBUG (MainThread) [websockets.server] < origin: {MANUAL HIDDEN}
2024-11-02 19:58:28.993 DEBUG (MainThread) [websockets.server] < accept: */*
2024-11-02 19:58:28.993 DEBUG (MainThread) [websockets.server] < user-agent: AHC/2.1
2024-11-02 19:58:28.993 DEBUG (MainThread) [websockets.server] > HTTP/1.1 101 Switching Protocols
2024-11-02 19:58:28.993 DEBUG (MainThread) [websockets.server] > Upgrade: websocket
2024-11-02 19:58:28.993 DEBUG (MainThread) [websockets.server] > Connection: Upgrade
2024-11-02 19:58:28.993 DEBUG (MainThread) [websockets.server] > Sec-WebSocket-Accept: Qsio951wG5Q1/VaydMDk7E8ju7A=
2024-11-02 19:58:28.993 DEBUG (MainThread) [websockets.server] > Sec-WebSocket-Protocol: ocpp1.6
2024-11-02 19:58:28.993 DEBUG (MainThread) [websockets.server] > Date: Sat, 02 Nov 2024 18:58:28 GMT
2024-11-02 19:58:28.994 DEBUG (MainThread) [websockets.server] > Server: Python/3.12 websockets/13.1
2024-11-02 19:58:28.994 INFO (MainThread) [websockets.server] connection open
2024-11-02 19:58:28.994 DEBUG (MainThread) [websockets.server] = connection is OPEN
2024-11-02 19:58:28.995 INFO (MainThread) [custom_components.ocpp] Websocket Subprotocol matched: ocpp1.6
2024-11-02 19:58:28.995 INFO (MainThread) [custom_components.ocpp] Charger websocket path=/SMP_6120001832
2024-11-02 19:58:28.995 INFO (MainThread) [custom_components.ocpp] Charger SMP_6120001832 connected to 0.0.0.0:9000.
2024-11-02 19:58:29.240 DEBUG (MainThread) [websockets.server] < TEXT '[2,"6c7bc708-1da9-47d0-bbfc-825286a5eab5","Heartbeat",{}]' [57 bytes]
2024-11-02 19:58:29.241 INFO (MainThread) [ocpp] SMP_6120001832: receive message [2,"6c7bc708-1da9-47d0-bbfc-825286a5eab5","Heartbeat",{}]
2024-11-02 19:58:29.256 WARNING (MainThread) [homeassistant.util.loop] Detected blocking call to open with args ('/usr/local/lib/python3.12/site-packages/ocpp/v16/schemas/Heartbeat.json', 'r') inside the event loop by custom integration 'ocpp' at custom_components/ocpp/api.py, line 1025: await super()._handle_call(msg) (offender: /usr/local/lib/python3.12/site-packages/ocpp/messages.py, line 164: with open(path, "r", encoding="utf-8-sig") as f:), **please create a bug report at https://github.com/lbbrhzn/ocpp/issues**
For developers, please see https://developers.home-assistant.io/docs/asyncio_blocking_operations/#open
Traceback (most recent call last):
  File "<frozen runpy>", line 198, in _run_module_as_main
  File "<frozen runpy>", line 88, in _run_code
  File "/usr/src/homeassistant/homeassistant/__main__.py", line 223, in <module>
    sys.exit(main())
  File "/usr/src/homeassistant/homeassistant/__main__.py", line 209, in main
    exit_code = runner.run(runtime_conf)
  File "/usr/src/homeassistant/homeassistant/runner.py", line 189, in run
    return loop.run_until_complete(setup_and_run_hass(runtime_config))
  File "/usr/local/lib/python3.12/asyncio/base_events.py", line 674, in run_until_complete
    self.run_forever()
  File "/usr/local/lib/python3.12/asyncio/base_events.py", line 641, in run_forever
    self._run_once()
  File "/usr/local/lib/python3.12/asyncio/base_events.py", line 1990, in _run_once
    handle._run()
  File "/usr/local/lib/python3.12/asyncio/events.py", line 88, in _run
    self._context.run(self._callback, *self._args)
  File "/usr/local/lib/python3.12/site-packages/ocpp/charge_point.py", line 238, in start
    await self.route_message(message)
  File "/usr/local/lib/python3.12/site-packages/ocpp/charge_point.py", line 261, in route_message
    await self._handle_call(msg)
  File "/config/custom_components/ocpp/api.py", line 1025, in _handle_call
    await super()._handle_call(msg)

2024-11-02 19:58:29.278 INFO (MainThread) [ocpp] SMP_6120001832: send [3,"6c7bc708-1da9-47d0-bbfc-825286a5eab5",{"currentTime":"2024-11-02T18:58:29Z"}]
2024-11-02 19:58:29.278 DEBUG (MainThread) [websockets.server] > TEXT '[3,"6c7bc708-1da9-47d0-bbfc-825286a5eab5",{"cur...2024-11-02T18:58:29Z"}]' [81 bytes]
2024-11-02 19:58:31.016 INFO (MainThread) [ocpp] SMP_6120001832: send [2,"dfc73451-7dab-4ebf-808c-2404b47eebb0","GetConfiguration",{"key":["SupportedFeatureProfiles"]}]
2024-11-02 19:58:31.016 DEBUG (MainThread) [websockets.server] > TEXT '[2,"dfc73451-7dab-4ebf-808c-2404b47eebb0","GetC...rtedFeatureProfiles"]}]' [98 bytes]
2024-11-02 19:58:31.069 DEBUG (MainThread) [websockets.server] < TEXT '[3,"dfc73451-7dab-4ebf-808c-2404b47eebb0",{"con...er"}],"unknownKey":[]}]' [162 bytes]
2024-11-02 19:58:31.069 INFO (MainThread) [ocpp] SMP_6120001832: receive message [3,"dfc73451-7dab-4ebf-808c-2404b47eebb0",{"configurationKey":[{"key":"SupportedFeatureProfiles","readonly":true,"value":"Core, RemoteTrigger"}],"unknownKey":[]}]
2024-11-02 19:58:31.092 DEBUG (MainThread) [custom_components.ocpp] Feature profiles returned: Profiles.CORE|REM
2024-11-02 19:58:31.100 INFO (MainThread) [ocpp] SMP_6120001832: send [2,"258addae-7c9b-40d5-ac76-e89e441d66f9","GetConfiguration",{"key":["NumberOfConnectors"]}]
2024-11-02 19:58:31.100 DEBUG (MainThread) [websockets.server] > TEXT '[2,"258addae-7c9b-40d5-ac76-e89e441d66f9","GetC..."NumberOfConnectors"]}]' [92 bytes]
2024-11-02 19:58:31.140 DEBUG (MainThread) [websockets.server] < TEXT '[3,"258addae-7c9b-40d5-ac76-e89e441d66f9",{"con..."1"}],"unknownKey":[]}]' [138 bytes]
2024-11-02 19:58:31.140 INFO (MainThread) [ocpp] SMP_6120001832: receive message [3,"258addae-7c9b-40d5-ac76-e89e441d66f9",{"configurationKey":[{"key":"NumberOfConnectors","readonly":true,"value":"1"}],"unknownKey":[]}]
2024-11-02 19:58:31.142 DEBUG (MainThread) [custom_components.ocpp] Get Configuration for NumberOfConnectors: 1
2024-11-02 19:58:31.143 INFO (MainThread) [ocpp] SMP_6120001832: send [2,"4887bfec-0006-47a7-b688-9e2f5d2bad2e","GetConfiguration",{"key":["HeartbeatInterval"]}]
2024-11-02 19:58:31.143 DEBUG (MainThread) [websockets.server] > TEXT '[2,"4887bfec-0006-47a7-b688-9e2f5d2bad2e","GetC...["HeartbeatInterval"]}]' [91 bytes]
2024-11-02 19:58:31.218 DEBUG (MainThread) [websockets.server] < TEXT '[3,"4887bfec-0006-47a7-b688-9e2f5d2bad2e",{"con...00"}],"unknownKey":[]}]' [141 bytes]
2024-11-02 19:58:31.219 INFO (MainThread) [ocpp] SMP_6120001832: receive message [3,"4887bfec-0006-47a7-b688-9e2f5d2bad2e",{"configurationKey":[{"key":"HeartbeatInterval","readonly":false,"value":"3600"}],"unknownKey":[]}]
2024-11-02 19:58:31.221 DEBUG (MainThread) [custom_components.ocpp] Get Configuration for HeartbeatInterval: 3600
2024-11-02 19:58:31.221 DEBUG (MainThread) [custom_components.ocpp] 'SMP_6120001832' trying measurand: ''
2024-11-02 19:58:31.241 INFO (MainThread) [ocpp] SMP_6120001832: send [2,"22bb635e-f483-4e42-9349-3999bedb7817","ChangeConfiguration",{"key":"MeterValuesSampledData","value":""}]
2024-11-02 19:58:31.241 DEBUG (MainThread) [websockets.server] > TEXT '[2,"22bb635e-f483-4e42-9349-3999bedb7817","Chan...mpledData","value":""}]' [108 bytes]
2024-11-02 19:58:31.271 DEBUG (MainThread) [websockets.server] < TEXT '[3,"22bb635e-f483-4e42-9349-3999bedb7817",{"status":"Rejected"}]' [64 bytes]
2024-11-02 19:58:31.273 INFO (MainThread) [ocpp] SMP_6120001832: receive message [3,"22bb635e-f483-4e42-9349-3999bedb7817",{"status":"Rejected"}]
2024-11-02 19:58:31.290 INFO (MainThread) [ocpp] SMP_6120001832: send [2,"c3263e82-c7ce-4c5e-8a3a-567773c20afe","GetConfiguration",{"key":["MeterValuesSampledData"]}]
2024-11-02 19:58:31.290 DEBUG (MainThread) [websockets.server] > TEXT '[2,"c3263e82-c7ce-4c5e-8a3a-567773c20afe","GetC...erValuesSampledData"]}]' [96 bytes]
2024-11-02 19:58:31.318 DEBUG (MainThread) [websockets.server] < TEXT '[3,"c3263e82-c7ce-4c5e-8a3a-567773c20afe",{"con...re"}],"unknownKey":[]}]' [229 bytes]
2024-11-02 19:58:31.319 INFO (MainThread) [ocpp] SMP_6120001832: receive message [3,"c3263e82-c7ce-4c5e-8a3a-567773c20afe",{"configurationKey":[{"key":"MeterValuesSampledData","readonly":true,"value":"Energy.Active.Import.Register, Power.Active.Import, Current.Import, Voltage, Temperature"}],"unknownKey":[]}]
2024-11-02 19:58:31.321 DEBUG (MainThread) [custom_components.ocpp] Get Configuration for MeterValuesSampledData: Energy.Active.Import.Register, Power.Active.Import, Current.Import, Voltage, Temperature
2024-11-02 19:58:31.321 DEBUG (MainThread) [custom_components.ocpp] 'SMP_6120001832' measurands not configurable by integration
2024-11-02 19:58:31.322 DEBUG (MainThread) [custom_components.ocpp] 'SMP_6120001832' allowed measurands: 'Energy.Active.Import.Register, Power.Active.Import, Current.Import, Voltage, Temperature'
2024-11-02 19:58:31.323 INFO (MainThread) [ocpp] SMP_6120001832: send [2,"b94ef7ea-b8c8-4192-9c6b-f807f57a6aa0","GetConfiguration",{"key":["MeterValueSampleInterval"]}]
2024-11-02 19:58:31.323 DEBUG (MainThread) [websockets.server] > TEXT '[2,"b94ef7ea-b8c8-4192-9c6b-f807f57a6aa0","GetC...ValueSampleInterval"]}]' [98 bytes]
2024-11-02 19:58:31.393 DEBUG (MainThread) [websockets.server] < TEXT '[3,"b94ef7ea-b8c8-4192-9c6b-f807f57a6aa0",{"con...60"}],"unknownKey":[]}]' [146 bytes]
2024-11-02 19:58:31.394 INFO (MainThread) [ocpp] SMP_6120001832: receive message [3,"b94ef7ea-b8c8-4192-9c6b-f807f57a6aa0",{"configurationKey":[{"key":"MeterValueSampleInterval","readonly":false,"value":"60"}],"unknownKey":[]}]
2024-11-02 19:58:31.395 INFO (MainThread) [ocpp] SMP_6120001832: send [2,"40eccea5-54b6-4fc3-94ce-86c229d3283e","GetConfiguration",{"key":["ClockAlignedDataInterval"]}]
2024-11-02 19:58:31.395 DEBUG (MainThread) [websockets.server] > TEXT '[2,"40eccea5-54b6-4fc3-94ce-86c229d3283e","GetC...AlignedDataInterval"]}]' [98 bytes]
2024-11-02 19:58:31.463 DEBUG (MainThread) [websockets.server] < TEXT '[3,"40eccea5-54b6-4fc3-94ce-86c229d3283e",{"con...00"}],"unknownKey":[]}]' [147 bytes]
2024-11-02 19:58:31.463 INFO (MainThread) [ocpp] SMP_6120001832: receive message [3,"40eccea5-54b6-4fc3-94ce-86c229d3283e",{"configurationKey":[{"key":"ClockAlignedDataInterval","readonly":false,"value":"900"}],"unknownKey":[]}]
2024-11-02 19:58:31.464 DEBUG (MainThread) [custom_components.ocpp] 'SMP_6120001832' post connection setup completed successfully
2024-11-02 19:58:31.464 INFO (MainThread) [ocpp] SMP_6120001832: send [2,"2e501469-7b67-4d51-845e-8ffe21f1e2e4","GetConfiguration",{"key":["WebSocketPingInterval"]}]
2024-11-02 19:58:31.465 DEBUG (MainThread) [websockets.server] > TEXT '[2,"2e501469-7b67-4d51-845e-8ffe21f1e2e4","GetC...bSocketPingInterval"]}]' [95 bytes]
2024-11-02 19:58:31.530 DEBUG (MainThread) [websockets.server] < TEXT '[3,"2e501469-7b67-4d51-845e-8ffe21f1e2e4",{"con...60"}],"unknownKey":[]}]' [142 bytes]
2024-11-02 19:58:31.530 INFO (MainThread) [ocpp] SMP_6120001832: receive message [3,"2e501469-7b67-4d51-845e-8ffe21f1e2e4",{"configurationKey":[{"key":"WebSocketPingInterval","readonly":true,"value":"60"}],"unknownKey":[]}]
2024-11-02 19:58:31.542 INFO (MainThread) [ocpp] SMP_6120001832: send [2,"0fae2a54-b787-485d-86c4-585fdba5384c","ChangeAvailability",{"connectorId":0,"type":"Operative"}]
2024-11-02 19:58:31.543 DEBUG (MainThread) [websockets.server] > TEXT '[2,"0fae2a54-b787-485d-86c4-585fdba5384c","Chan...:0,"type":"Operative"}]' [100 bytes]
2024-11-02 19:58:31.579 DEBUG (MainThread) [websockets.server] < TEXT '[3,"0fae2a54-b787-485d-86c4-585fdba5384c",{"status":"Accepted"}]' [64 bytes]
2024-11-02 19:58:31.579 INFO (MainThread) [ocpp] SMP_6120001832: receive message [3,"0fae2a54-b787-485d-86c4-585fdba5384c",{"status":"Accepted"}]
2024-11-02 19:58:31.596 INFO (MainThread) [ocpp] SMP_6120001832: send [2,"21e02b86-ce0d-4784-b2ec-b0be581df6b1","TriggerMessage",{"requestedMessage":"BootNotification"}]
2024-11-02 19:58:31.596 DEBUG (MainThread) [websockets.server] > TEXT '[2,"21e02b86-ce0d-4784-b2ec-b0be581df6b1","Trig...e":"BootNotification"}]' [99 bytes]
2024-11-02 19:58:31.625 DEBUG (MainThread) [websockets.server] < TEXT '[3,"21e02b86-ce0d-4784-b2ec-b0be581df6b1",{"status":"Accepted"}]' [64 bytes]
2024-11-02 19:58:31.625 INFO (MainThread) [ocpp] SMP_6120001832: receive message [3,"21e02b86-ce0d-4784-b2ec-b0be581df6b1",{"status":"Accepted"}]
2024-11-02 19:58:31.634 DEBUG (MainThread) [custom_components.ocpp] trigger status notification for connector=0
2024-11-02 19:58:31.635 INFO (MainThread) [ocpp] SMP_6120001832: send [2,"92472ce1-1574-435e-9d5a-ce97b07c6953","TriggerMessage",{"requestedMessage":"StatusNotification","connectorId":0}]
2024-11-02 19:58:31.635 DEBUG (MainThread) [websockets.server] > TEXT '[2,"92472ce1-1574-435e-9d5a-ce97b07c6953","Trig...tion","connectorId":0}]' [117 bytes]
2024-11-02 19:58:31.670 DEBUG (MainThread) [websockets.server] < TEXT '[3,"92472ce1-1574-435e-9d5a-ce97b07c6953",{"status":"Rejected"}]' [64 bytes]
2024-11-02 19:58:31.670 INFO (MainThread) [ocpp] SMP_6120001832: receive message [3,"92472ce1-1574-435e-9d5a-ce97b07c6953",{"status":"Rejected"}]
2024-11-02 19:58:31.670 WARNING (MainThread) [custom_components.ocpp] Failed with response: Rejected
2024-11-02 19:58:31.671 DEBUG (MainThread) [custom_components.ocpp] trigger status notification for connector=1
2024-11-02 19:58:31.671 INFO (MainThread) [ocpp] SMP_6120001832: send [2,"6b0126b0-cf64-484a-8ab6-9c8dcb7ea013","TriggerMessage",{"requestedMessage":"StatusNotification","connectorId":1}]
2024-11-02 19:58:31.671 DEBUG (MainThread) [websockets.server] > TEXT '[2,"6b0126b0-cf64-484a-8ab6-9c8dcb7ea013","Trig...tion","connectorId":1}]' [117 bytes]
2024-11-02 19:58:31.738 DEBUG (MainThread) [websockets.server] < TEXT '[3,"6b0126b0-cf64-484a-8ab6-9c8dcb7ea013",{"status":"Rejected"}]' [64 bytes]
2024-11-02 19:58:31.739 INFO (MainThread) [ocpp] SMP_6120001832: receive message [3,"6b0126b0-cf64-484a-8ab6-9c8dcb7ea013",{"status":"Rejected"}]
2024-11-02 19:58:31.739 WARNING (MainThread) [custom_components.ocpp] Failed with response: Rejected
2024-11-02 19:58:31.840 DEBUG (MainThread) [websockets.server] < TEXT '[2,"77cbabc7-b474-483f-8892-029ca5841ab7","Boot...rsion":"OCPPJ 1.21.0"}]' [244 bytes]
2024-11-02 19:58:31.840 INFO (MainThread) [ocpp] SMP_6120001832: receive message [2,"77cbabc7-b474-483f-8892-029ca5841ab7","BootNotification",{"chargePointModel":"EVWB-332-C8R-E-B","chargePointVendor":"Smappee","chargeBoxSerialNumber":"5130052149","chargePointSerialNumber":"SMP_6120001832","firmwareVersion":"OCPPJ 1.21.0"}]
2024-11-02 19:58:31.852 DEBUG (MainThread) [custom_components.ocpp] Received boot notification for SMP_6120001832: {'charge_point_model': 'EVWB-332-C8R-E-B', 'charge_point_vendor': 'Smappee', 'charge_box_serial_number': '5130052149', 'charge_point_serial_number': 'SMP_6120001832', 'firmware_version': 'OCPPJ 1.21.0'}
2024-11-02 19:58:31.852 DEBUG (MainThread) [custom_components.ocpp] Updating device info charger: {'charge_point_model': 'EVWB-332-C8R-E-B', 'charge_point_vendor': 'Smappee', 'charge_box_serial_number': '5130052149', 'charge_point_serial_number': 'SMP_6120001832', 'firmware_version': 'OCPPJ 1.21.0'}
2024-11-02 19:58:31.874 INFO (MainThread) [ocpp] SMP_6120001832: send [3,"77cbabc7-b474-483f-8892-029ca5841ab7",{"currentTime":"2024-11-02T18:58:31Z","interval":3600,"status":"Accepted"}]
2024-11-02 19:58:31.875 DEBUG (MainThread) [websockets.server] > TEXT '[3,"77cbabc7-b474-483f-8892-029ca5841ab7",{"cur...0,"status":"Accepted"}]' [117 bytes]
2024-11-02 19:58:31.952 DEBUG (MainThread) [websockets.server] < TEXT '[2,"0c3d1d59-97c9-4a49-b7cb-916b756804b1","Stat...,"status":"Available"}]' [124 bytes]
2024-11-02 19:58:31.953 INFO (MainThread) [ocpp] SMP_6120001832: receive message [2,"0c3d1d59-97c9-4a49-b7cb-916b756804b1","StatusNotification",{"connectorId":1,"errorCode":"NoError","status":"Available"}]
2024-11-02 19:58:31.978 INFO (MainThread) [ocpp] SMP_6120001832: send [3,"0c3d1d59-97c9-4a49-b7cb-916b756804b1",{}]
2024-11-02 19:58:31.978 DEBUG (MainThread) [websockets.server] > TEXT '[3,"0c3d1d59-97c9-4a49-b7cb-916b756804b1",{}]' [45 bytes]
2024-11-02 19:58:32.202 DEBUG (MainThread) [websockets.server] < TEXT '[2,"0de7db7d-e967-4cbe-befb-a255fc40af3c","Heartbeat",{}]' [57 bytes]
2024-11-02 19:58:32.203 INFO (MainThread) [ocpp] SMP_6120001832: receive message [2,"0de7db7d-e967-4cbe-befb-a255fc40af3c","Heartbeat",{}]
2024-11-02 19:58:32.208 INFO (MainThread) [ocpp] SMP_6120001832: send [3,"0de7db7d-e967-4cbe-befb-a255fc40af3c",{"currentTime":"2024-11-02T18:58:32Z"}]
2024-11-02 19:58:32.209 DEBUG (MainThread) [websockets.server] > TEXT '[3,"0de7db7d-e967-4cbe-befb-a255fc40af3c",{"cur...2024-11-02T18:58:32Z"}]' [81 bytes]

2024-11-02 19:58:49.087 DEBUG (MainThread) [websockets.server] > PING cb 72 75 96 [binary, 4 bytes]
2024-11-02 19:58:49.273 DEBUG (MainThread) [websockets.server] < PONG cb 72 75 96 [binary, 4 bytes]
2024-11-02 19:58:49.308 DEBUG (MainThread) [custom_components.ocpp] Connection latency from 'central' to 'SMP_6120001832': ping=4.0 ms, pong=217.0 ms
2024-11-02 19:58:52.967 WARNING (Recorder) [homeassistant.components.recorder.db_schema] State attributes for sensor.energy_electricity_prices_daily exceed maximum size of 16384 bytes. This can cause database performance issues; Attributes will not be stored
2024-11-02 19:58:53.913 WARNING (Recorder) [homeassistant.components.recorder.db_schema] State attributes for sensor.energy_electricity_prices_daily exceed maximum size of 16384 bytes. This can cause database performance issues; Attributes will not be stored
2024-11-02 19:59:09.309 DEBUG (MainThread) [websockets.server] > PING c3 1a 4a 24 [binary, 4 bytes]
2024-11-02 19:59:09.333 DEBUG (MainThread) [websockets.server] < PONG c3 1a 4a 24 [binary, 4 bytes]
2024-11-02 19:59:09.334 DEBUG (MainThread) [custom_components.ocpp] Connection latency from 'central' to 'SMP_6120001832': ping=1.0 ms, pong=24.0 ms
2024-11-02 19:59:24.019 DEBUG (MainThread) [websockets.server] < PING '' [0 bytes]
2024-11-02 19:59:24.019 DEBUG (MainThread) [websockets.server] > PONG '' [0 bytes]
2024-11-02 19:59:25.740 INFO (MainThread) [custom_components.ocpp] Start transaction with remote ID tag: 88URI6DQH3245Q9PZTXC
2024-11-02 19:59:25.752 INFO (MainThread) [ocpp] SMP_6120001832: send [2,"e5b547cb-ce77-4b0d-991d-5d8c5256dded","RemoteStartTransaction",{"idTag":"88URI6DQH3245Q9PZTXC","connectorId":1}]
2024-11-02 19:59:25.752 DEBUG (MainThread) [websockets.server] > TEXT '[2,"e5b547cb-ce77-4b0d-991d-5d8c5256dded","Remo...ZTXC","connectorId":1}]' [116 bytes]
2024-11-02 19:59:25.782 DEBUG (MainThread) [websockets.server] < TEXT '[3,"e5b547cb-ce77-4b0d-991d-5d8c5256dded",{"status":"Rejected"}]' [64 bytes]
2024-11-02 19:59:25.782 INFO (MainThread) [ocpp] SMP_6120001832: receive message [3,"e5b547cb-ce77-4b0d-991d-5d8c5256dded",{"status":"Rejected"}]
2024-11-02 19:59:25.793 WARNING (MainThread) [custom_components.ocpp] Failed with response: Rejected
2024-11-02 19:59:29.335 DEBUG (MainThread) [websockets.server] > PING 35 8e c0 5a [binary, 4 bytes]
2024-11-02 19:59:29.362 DEBUG (MainThread) [websockets.server] < PONG 35 8e c0 5a [binary, 4 bytes]
2024-11-02 19:59:29.371 DEBUG (MainThread) [custom_components.ocpp] Connection latency from 'central' to 'SMP_6120001832': ping=2.0 ms, pong=34.0 ms

```

**Comment by clousberg** [comment]
any idea how to get this one forward ??
I also would like to help analyzing and maybe solving part of it (I'm a software developer myself, but don't have the knowledge how to get this one forward.....)
Thanks!

**Comment by clousberg** [comment]
any idea how to get this one forward ??
I also would like to help analyzing and maybe solving part of it (I'm a software developer myself, but don't have the knowledge how to get this one forward.....)
Thanks!
