### ISSUE TITLE
Debug logs requested this bug be raised:

### ISSUE THREAD

**Issue by arh-au** [lbbrhzn/ocpp#1402]
**Describe the bug**
Logs requested to log this bug

**To Reproduce**
1. Enabled new charger to use OCPP 
2. Registration process started on Home Assistant
3. See copy of logs below requesting issue to be raised

**Charger details::**
 - Device: LINCHR 7kw untethered charger (https://www.linchrevcharger.com/sale-36699777-ev-box-home-charger-type-2-32a-iec-61851-1-plug-in-7kw-ev-car-home-charging-station.html)
 - Further details below in log

**Log Content**
2024-11-24 15:29:43.681 DEBUG (MainThread) [websockets.server] = connection is CONNECTING
2024-11-24 15:29:43.688 DEBUG (MainThread) [websockets.server] < GET /LINCHR7123050003103101050209A00 HTTP/1.1
2024-11-24 15:29:43.688 DEBUG (MainThread) [websockets.server] < Host: homeassistant.fritz.box:9000
2024-11-24 15:29:43.689 DEBUG (MainThread) [websockets.server] < Upgrade: websocket
2024-11-24 15:29:43.689 DEBUG (MainThread) [websockets.server] < Connection: Upgrade
2024-11-24 15:29:43.690 DEBUG (MainThread) [websockets.server] < Sec-WebSocket-Key: YmfeBIbpyZpGOD8lZuNigQ==
2024-11-24 15:29:43.690 DEBUG (MainThread) [websockets.server] < Sec-WebSocket-Version: 13
2024-11-24 15:29:43.690 DEBUG (MainThread) [websockets.server] < Sec-WebSocket-Protocol: ocpp1.6
2024-11-24 15:29:43.691 DEBUG (MainThread) [websockets.server] > HTTP/1.1 101 Switching Protocols
2024-11-24 15:29:43.692 DEBUG (MainThread) [websockets.server] > Upgrade: websocket
2024-11-24 15:29:43.692 DEBUG (MainThread) [websockets.server] > Connection: Upgrade
2024-11-24 15:29:43.692 DEBUG (MainThread) [websockets.server] > Sec-WebSocket-Accept: QKSz760pTG56RTJDO8rLG/Hj5t0=
2024-11-24 15:29:43.692 DEBUG (MainThread) [websockets.server] > Sec-WebSocket-Protocol: ocpp1.6
2024-11-24 15:29:43.693 DEBUG (MainThread) [websockets.server] > Date: Sun, 24 Nov 2024 05:29:43 GMT
2024-11-24 15:29:43.693 DEBUG (MainThread) [websockets.server] > Server: Python/3.12 websockets/13.1
2024-11-24 15:29:43.694 INFO (MainThread) [websockets.server] connection open
2024-11-24 15:29:43.695 DEBUG (MainThread) [websockets.server] = connection is OPEN
2024-11-24 15:29:43.696 INFO (MainThread) [custom_components.ocpp] Websocket Subprotocol matched: ocpp1.6
2024-11-24 15:29:43.696 INFO (MainThread) [custom_components.ocpp] Charger websocket path=/LINCHR7123050003103101050209A00
2024-11-24 15:29:43.696 INFO (MainThread) [custom_components.ocpp] Charger LINCHR7123050003103101050209A00 connected to 0.0.0.0:9000.
2024-11-24 15:29:44.753 DEBUG (MainThread) [websockets.server] < TEXT '[2,"1232effd-0b03-4f94-99cb-6c6d1fa1c452","Boot...eterType":"PRO-1 MOD"}]' [277 bytes]
2024-11-24 15:29:44.761 INFO (MainThread) [ocpp] LINCHR7123050003103101050209A00: receive message [2,"1232effd-0b03-4f94-99cb-6c6d1fa1c452","BootNotification",{"chargePointModel":"AC_7KW_001","chargePointSerialNumber":"7123050003103101050209A00","chargePointVendor":"LINCHR","firmwareVersion":"83105120000_JLS2103_V104B00D01","meterSerialNumber":"0","meterType":"PRO-1 MOD"}]
2024-11-24 15:29:44.968 WARNING (MainThread) [homeassistant.util.loop] Detected blocking call to open with args ('/usr/local/lib/python3.12/site-packages/ocpp/v16/schemas/BootNotification.json', 'r') inside the event loop by custom integration 'ocpp' at custom_components/ocpp/api.py, line 1025: await super()._handle_call(msg) (offender: /usr/local/lib/python3.12/site-packages/ocpp/messages.py, line 164: with open(path, "r", encoding="utf-8-sig") as f:), **please create a bug report at https://github.com/lbbrhzn/ocpp/issues**
For developers, please see https://developers.home-assistant.io/docs/asyncio_blocking_operations/#open
Traceback (most recent call last):
  File "<frozen runpy>", line 198, in _run_module_as_main
  File "<frozen runpy>", line 88, in _run_code
  File "/usr/src/homeassistant/homeassistant/__main__.py", line 223, in <module>
    sys.exit(main())
  File "/usr/src/homeassistant/homeassistant/__main__.py", line 209, in main
    exit_code = runner.run(runtime_conf)
  File "/usr/src/homeassistant/homeassistant/runner.py", line 189, in run
    return loop.run_until_complete(setup_and_run_hass(runtime_config))
  File "/usr/local/lib/python3.12/asyncio/base_events.py", line 674, in run_until_complete
    self.run_forever()
  File "/usr/local/lib/python3.12/asyncio/base_events.py", line 641, in run_forever
    self._run_once()
  File "/usr/local/lib/python3.12/asyncio/base_events.py", line 1990, in _run_once
    handle._run()
  File "/usr/local/lib/python3.12/asyncio/events.py", line 88, in _run
    self._context.run(self._callback, *self._args)
  File "/usr/local/lib/python3.12/site-packages/ocpp/charge_point.py", line 238, in start
    await self.route_message(message)
  File "/usr/local/lib/python3.12/site-packages/ocpp/charge_point.py", line 261, in route_message
    await self._handle_call(msg)
  File "/config/custom_components/ocpp/api.py", line 1025, in _handle_call
    await super()._handle_call(msg)
2024-11-24 15:29:45.011 DEBUG (MainThread) [custom_components.ocpp] Received boot notification for LINCHR7123050003103101050209A00: {'charge_point_model': 'AC_7KW_001', 'charge_point_serial_number': '7123050003103101050209A00', 'charge_point_vendor': 'LINCHR', 'firmware_version': '83105120000_JLS2103_V104B00D01', 'meter_serial_number': '0', 'meter_type': 'PRO-1 MOD'}
2024-11-24 15:29:45.012 DEBUG (MainThread) [custom_components.ocpp] Updating device info charger: {'charge_point_model': 'AC_7KW_001', 'charge_point_serial_number': '7123050003103101050209A00', 'charge_point_vendor': 'LINCHR', 'firmware_version': '83105120000_JLS2103_V104B00D01', 'meter_serial_number': '0', 'meter_type': 'PRO-1 MOD'}
2024-11-24 15:29:45.133 INFO (MainThread) [ocpp] LINCHR7123050003103101050209A00: send [3,"1232effd-0b03-4f94-99cb-6c6d1fa1c452",{"currentTime":"2024-11-24T05:29:45Z","interval":3600,"status":"Accepted"}]

**Comment by clousberg** [comment]
equal to my ticket #1384
