### ISSUE TITLE
Error related to 'idle_interval'

### ISSUE THREAD

**Issue by lbbrhzn** [lbbrhzn/ocpp#295]
## Version of the custom_component

unreleased

## Configuration

N/A

## Describe the bug

An error occured related to 'idle_interval' when running tests on the main branch.

## Debug log

```text
ERROR:custom_components.ocpp:Exception occurred:
'idle_interval'
Traceback (most recent call last):
  File "/home/runner/work/ocpp/ocpp/custom_components/ocpp/api.py", line 183, in on_connect
    await charge_point.start()
  File "/home/runner/work/ocpp/ocpp/custom_components/ocpp/api.py", line 764, in start
    await asyncio.gather(super().start(), self.post_connect())
  File "/home/runner/work/ocpp/ocpp/custom_components/ocpp/api.py", line 379, in post_connect
    str(self.entry.data[CONF_IDLE_INTERVAL]),
KeyError: 'idle_interval'
INFO:custom_components.ocpp:Charger CP_1 disconnected from 127.0.0.1:9000.
INFO:websockets.server:connection closed
```

**Comment by drc38** [comment]
Fixed with commit https://github.com/lbbrhzn/ocpp/commit/93ac9dacb3cdfefa66fab24885ee24316dcec781
