### ISSUE TITLE
KeyError: 'measurand' in new intergation

### ISSUE THREAD

**Issue by Rep-Hueman** [lbbrhzn/ocpp#44]
New Intergration not working.
I deleted the existing configuration in configuration.yaml.

Old intergation config

```
  - platform: ocpp
    name: charger_alfen
    meter_interval: 60
    monitored_variables:
      - "Energy.Active.Import.Register"
      - "Current.Import"
      - "Current.Offered"
      - "Frequency"
      - "Power.Active.Import"
      - "Power.Factor"
      - "Temperature"
      - "Voltage"
    port: 9000
    scan_interval:
      seconds: 60
```

New intergation version 0.2 (code copy on 06-07-2021)
What should I select now for sensors?
I have tried several sensors here...

```
Instantaneous current flow from EV
Instantaneous current flow to EV
Maximum current offered to EV
Active energy exported to the grid
Active energy imported from the grid
Reactive energy exported to the grid
Reactive energy imported from the grid
Active energy exported to the grid during last interval
Active energy imported from the grid during last interval
Reactive energy exported to the grid during last interval
Reactive energy imported from the grid during last interval
Powerline frequency
Instantaneous active power exported by EV
Instantaneous active power imported by EV
Instantaneous power factor of total energy flow
Maximum power offered to EV
Instantaneous reactive power exported by EV
Instantaneous reactive power imported by EV
Fan speed in RPM
State of charge of EV in percentage
Temperature reading inside Charge Point
Instantaneous AC RMS supply voltage
```

OCPP
Version 0.2  code copy on 06-07-2021

## Describe the bug
KeyError: 'measurand' in new intergation

## Debug log
```
2021-07-06 13:25:13 INFO (MainThread) [ocpp] Alfen-Beheer: send [2,"6587298c-1c82-4d09-b971-879ceb1a2ffc","GetConfiguration",{"key":["SupportedFeatureProfiles"]}]
2021-07-06 13:25:14 INFO (MainThread) [ocpp] Alfen-Beheer: receive message [3,"6587298c-1c82-4d09-b971-879ceb1a2ffc",{"configurationKey":[{"key":"SupportedFeatureProfiles","readonly":true,"value":"Core,FirmwareManagement,Reservation,LocalAuthListManagement,RemoteTrigger,SmartCharging"}]}]
2021-07-06 13:25:14 INFO (MainThread) [ocpp] Alfen-Beheer: send [2,"b7a7d021-3dc2-4623-ba2f-b2a673c760cd","TriggerMessage",{"requestedMessage":"BootNotification"}]
2021-07-06 13:25:14 INFO (MainThread) [ocpp] Alfen-Beheer: receive message [3,"b7a7d021-3dc2-4623-ba2f-b2a673c760cd",{"status":"Accepted"}]
2021-07-06 13:25:14 INFO (MainThread) [ocpp] Alfen-Beheer: send [2,"e3b0076e-0755-49a9-9985-05d730097e91","TriggerMessage",{"requestedMessage":"StatusNotification"}]
2021-07-06 13:25:14 INFO (MainThread) [ocpp] Alfen-Beheer: receive message [3,"e3b0076e-0755-49a9-9985-05d730097e91",{"status":"Rejected"}]
2021-07-06 13:25:14 INFO (MainThread) [ocpp] Alfen-Beheer: send [2,"bfec5b10-bc79-441c-808a-23a83056f104","ChangeAvailability",{"connectorId":0,"type":"Operative"}]
2021-07-06 13:25:14 INFO (MainThread) [ocpp] Alfen-Beheer: receive message [3,"bfec5b10-bc79-441c-808a-23a83056f104",{"status":"Accepted"}]
2021-07-06 13:25:14 INFO (MainThread) [ocpp] Alfen-Beheer: send [2,"4270d34e-8edc-407f-a39f-cbd8baaa7eca","GetConfiguration",{"key":["HeartbeatInterval"]}]
2021-07-06 13:25:14 INFO (MainThread) [ocpp] Alfen-Beheer: receive message [3,"4270d34e-8edc-407f-a39f-cbd8baaa7eca",{"configurationKey":[{"key":"HeartbeatInterval","readonly":false,"value":"900"}]}]
2021-07-06 13:25:14 INFO (MainThread) [ocpp] Alfen-Beheer: send [2,"acb6712c-3564-4136-a759-28bd1fc83fd4","GetConfiguration",{"key":["WebSocketPingInterval"]}]
2021-07-06 13:25:14 INFO (MainThread) [ocpp] Alfen-Beheer: receive message [3,"acb6712c-3564-4136-a759-28bd1fc83fd4",{"configurationKey":[{"key":"WebSocketPingInterval","readonly":false,"value":"60"}]}]
2021-07-06 13:25:14 INFO (MainThread) [ocpp] Alfen-Beheer: send [2,"7f2755e3-605a-4fbd-9081-616be8b95858","GetConfiguration",{"key":["MeterValuesSampledData"]}]
2021-07-06 13:25:14 INFO (MainThread) [ocpp] Alfen-Beheer: receive message [3,"7f2755e3-605a-4fbd-9081-616be8b95858",{"configurationKey":[{"key":"MeterValuesSampledData","readonly":false,"value":"Energy.Active.Import.Register"}]}]
2021-07-06 13:25:14 INFO (MainThread) [ocpp] Alfen-Beheer: send [2,"63a1e8a6-704d-46d9-a9fd-fb511ad44deb","ChangeConfiguration",{"key":"MeterValuesSampledData","value":"Energy.Active.Import.Register,Temperature"}]
2021-07-06 13:25:14 INFO (MainThread) [ocpp] Alfen-Beheer: receive message [3,"63a1e8a6-704d-46d9-a9fd-fb511ad44deb",{"status":"Accepted"}]
2021-07-06 13:25:14 INFO (MainThread) [ocpp] Alfen-Beheer: send [2,"72ec9fb8-d055-431e-8e70-7bda16f033d1","GetConfiguration",{"key":["MeterValueSampleInterval"]}]
2021-07-06 13:25:14 INFO (MainThread) [ocpp] Alfen-Beheer: receive message [3,"72ec9fb8-d055-431e-8e70-7bda16f033d1",{"configurationKey":[{"key":"MeterValueSampleInterval","readonly":false,"value":"60"}]}]
2021-07-06 13:25:14 INFO (MainThread) [ocpp] Alfen-Beheer: send [2,"020b7647-3a7b-44b4-aaf0-e736f59fe580","GetConfiguration",{"key":["NumberOfConnectors"]}]
2021-07-06 13:25:14 INFO (MainThread) [ocpp] Alfen-Beheer: receive message [3,"020b7647-3a7b-44b4-aaf0-e736f59fe580",{"configurationKey":[{"key":"NumberOfConnectors","readonly":true,"value":"1"}]}]
2021-07-06 13:25:19 INFO (MainThread) [ocpp] Alfen-Beheer: receive message [2,"1","BootNotification",{"chargePointVendor":"Alfen BV","chargePointModel":"NG910-60023","chargePointSerialNumber":"ace0025893","chargeBoxSerialNumber":"Reppel Beheer","firmwareVersion":"4.15.0-3910"}]
2021-07-06 13:25:19 INFO (MainThread) [ocpp] Alfen-Beheer: send [3,"1",{"currentTime":"2021-07-06T11:25:19.021947","interval":30,"status":"Accepted"}]
2021-07-06 13:25:53 INFO (MainThread) [ocpp] Alfen-Beheer: receive message [2,"2","MeterValues",{"connectorId":1,"transactionId":1625084784,"meterValue":[{"timestamp":"2021-06-30T20:27:07Z","sampledValue":[{"value":"1310.290","context":"Transaction.Begin","unit":"kWh"}]}]}]
2021-07-06 13:25:53 ERROR (MainThread) [ocpp] Error while handling request '<Call - unique_id=2, action=MeterValues, payload={'connectorId': 1, 'transactionId': 1625084784, 'meterValue': [{'timestamp': '2021-06-30T20:27:07Z', 'sampledValue': [{'value': '1310.290', 'context': 'Transaction.Begin', 'unit': 'kWh'}]}]}>'
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/site-packages/ocpp/charge_point.py", line 185, in _handle_call
    response = handler(**snake_case_payload)
  File "/usr/local/lib/python3.8/site-packages/ocpp/routing.py", line 33, in inner
    return func(*args, **kwargs)
  File "/config/custom_components/ocpp/api.py", line 473, in on_meter_values
    self._units[sampled_value["measurand"]] = sampled_value["unit"]
KeyError: 'measurand'
2021-07-06 13:25:53 INFO (MainThread) [ocpp] Alfen-Beheer: send [4,"2","InternalError","An unexpected error occurred.",{}]
2021-07-06 13:27:50 INFO (MainThread) [ocpp] Alfen-Beheer: receive message [2,"3","MeterValues",{"connectorId":1,"transactionId":1625084784,"meterValue":[{"timestamp":"2021-06-30T20:27:07Z","sampledValue":[{"value":"1310.290","context":"Transaction.Begin","unit":"kWh"}]}]}]
2021-07-06 13:27:50 ERROR (MainThread) [ocpp] Error while handling request '<Call - unique_id=3, action=MeterValues, payload={'connectorId': 1, 'transactionId': 1625084784, 'meterValue': [{'timestamp': '2021-06-30T20:27:07Z', 'sampledValue': [{'value': '1310.290', 'context': 'Transaction.Begin', 'unit': 'kWh'}]}]}>'
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/site-packages/ocpp/charge_point.py", line 185, in _handle_call
    response = handler(**snake_case_payload)
  File "/usr/local/lib/python3.8/site-packages/ocpp/routing.py", line 33, in inner
    return func(*args, **kwargs)
  File "/config/custom_components/ocpp/api.py", line 473, in on_meter_values
    self._units[sampled_value["measurand"]] = sampled_value["unit"]
KeyError: 'measurand'
2021-07-06 13:27:50 INFO (MainThread) [ocpp] Alfen-Beheer: send [4,"3","InternalError","An unexpected error occurred.",{}]
```

**Comment by Rep-Hueman** [comment]
I have found the translation :-)

```
                    "Energy.Active.Import.Register": "Active energy imported from the grid",
                    "Current.Import": "Instantaneous current flow to EV",
                    "Current.Offered": "Maximum current offered to EV",
                    "Frequency": "Powerline frequency",
                    "Power.Active.Import": "Instantaneous active power imported by EV",
                    "Power.Factor": "Instantaneous power factor of total energy flow",
                    "Temperature": "Temperature reading inside Charge Point",
                    "Voltage": "Instantaneous AC RMS supply voltage"
```

After restarting HA (Reboot host) and the Alfen charger **several times** it works 


..
