### ISSUE TITLE
Charger reconnects often after Firmware update

### ISSUE THREAD

**Issue by N3rdix** [lbbrhzn/ocpp#466]
My Vestel EVC04 charger updated its firmware today on its own and since that point in time the integration constantly generates persistent notification in home assistant while it is idle.

<img width="486" alt="image" src="https://user-images.githubusercontent.com/70015952/160688157-af89f00a-f0af-46eb-a65e-bd6b205cf6e2.png">

What I can see in the logs is the following below (at the same time the persistent notification pops up).

I did not start a charging cycle yet, not sure if this changes anything. Could the reason be an error on the manufacturer side by sending an empty value for sampledValue?

Full log:
```
2022-03-29 21:15:01 INFO (MainThread) [ocpp] Garage: receive message [2,"7106e13d-9867-417d-a711-b0023218ad22","MeterValues",{
    "connectorId": 1,
    "meterValue": [
        {
            "timestamp": "2022-03-29T19:15:00Z",
            "sampledValue": []
        }
    ]
}]
2022-03-29 21:15:01 ERROR (MainThread) [custom_components.ocpp] Unexpected exception in connection to 'Garage': 'Payload '{'connectorId': 1, 'meterValue': [{'timestamp': '2022-03-29T19:15:00Z', 'sampledValue': []}]} for action 'MeterValues' is not valid: [] is too short

Failed validating 'minItems' in schema['properties']['meterValue']['items']['properties']['sampledValue']:
    {'items': {'additionalProperties': False,
               'properties': {'context': {'additionalProperties': False,
                                          'enum': ['Interruption.Begin',
                                                   'Interruption.End',
                                                   'Sample.Clock',
                                                   'Sample.Periodic',
                                                   'Transaction.Begin',
                                                   'Transaction.End',
                                                   'Trigger',
                                                   'Other'],
                                          'type': 'string'},
                              'format': {'additionalProperties': False,
                                         'enum': ['Raw', 'SignedData'],
                                         'type': 'string'},
                              'location': {'additionalProperties': False,
                                           'enum': ['Cable',
                                                    'EV',
                                                    'Inlet',
                                                    'Outlet',
                                                    'Body'],
                                           'type': 'string'},
                              'measurand': {'additionalProperties': False,
                                            'enum': ['Energy.Active.Export.Register',
                                                     'Energy.Active.Import.Register',
                                                     'Energy.Reactive.Export.Register',
                                                     'Energy.Reactive.Import.Register',
                                                     'Energy.Active.Export.Interval',
                                                     'Energy.Active.Import.Interval',
                                                     'Energy.Reactive.Export.Interval',
                                                     'Energy.Reactive.Import.Interval',
                                                     'Power.Active.Export',
                                                     'Power.Active.Import',
                                                     'Power.Offered',
                                                     'Power.Reactive.Export',
                                                     'Power.Reactive.Import',
                                                     'Power.Factor',
                                                     'Current.Import',
                                                     'Current.Export',
                                                     'Current.Offered',
                                                     'Voltage',
                                                     'Frequency',
                                                     'Temperature',
                                                     'SoC',
                                                     'RPM'],
                                            'type': 'string'},
                              'phase': {'additionalProperties': False,
                                        'enum': ['L1',
                                                 'L2',
                                                 'L3',
                                                 'N',
                                                 'L1-N',
                                                 'L2-N',
                                                 'L3-N',
                                                 'L1-L2',
                                                 'L2-L3',
                                                 'L3-L1'],
                                        'type': 'string'},
                              'unit': {'additionalProperties': False,
                                       'enum': ['Wh',
                                                'kWh',
                                                'varh',
                                                'kvarh',
                                                'W',
                                                'kW',
                                                'VA',
                                                'kVA',
                                                'var',
                                                'kvar',
                                                'A',
                                                'V',
                                                'K',
                                                'Celcius',
                                                'Celsius',
                                                'Fahrenheit',
                                                'Percent',
                                                'Hertz'],
                                       'type': 'string'},
                              'value': {'type': 'string'}},
               'required': ['value'],
               'type': 'object'},
     'minItems': 1,
     'type': 'array'}

On instance['meterValue'][0]['sampledValue']:
    []'
Traceback (most recent call last):
  File "/usr/local/lib/python3.9/site-packages/ocpp/messages.py", line 192, in validate_payload
    validator.validate(message.payload)
  File "/usr/local/lib/python3.9/site-packages/jsonschema/validators.py", line 353, in validate
    raise error
jsonschema.exceptions.ValidationError: [] is too short

Failed validating 'minItems' in schema['properties']['meterValue']['items']['properties']['sampledValue']:
    {'items': {'additionalProperties': False,
               'properties': {'context': {'additionalProperties': False,
                                          'enum': ['Interruption.Begin',
                                                   'Interruption.End',
                                                   'Sample.Clock',
                                                   'Sample.Periodic',
                                                   'Transaction.Begin',
                                                   'Transaction.End',
                                                   'Trigger',
                                                   'Other'],
                                          'type': 'string'},
                              'format': {'additionalProperties': False,
                                         'enum': ['Raw', 'SignedData'],
                                         'type': 'string'},
                              'location': {'additionalProperties': False,
                                           'enum': ['Cable',
                                                    'EV',
                                                    'Inlet',
                                                    'Outlet',
                                                    'Body'],
                                           'type': 'string'},
                              'measurand': {'additionalProperties': False,
                                            'enum': ['Energy.Active.Export.Register',
                                                     'Energy.Active.Import.Register',
                                                     'Energy.Reactive.Export.Register',
                                                     'Energy.Reactive.Import.Register',
                                                     'Energy.Active.Export.Interval',
                                                     'Energy.Active.Import.Interval',
                                                     'Energy.Reactive.Export.Interval',
                                                     'Energy.Reactive.Import.Interval',
                                                     'Power.Active.Export',
                                                     'Power.Active.Import',
                                                     'Power.Offered',
                                                     'Power.Reactive.Export',
                                                     'Power.Reactive.Import',
                                                     'Power.Factor',
                                                     'Current.Import',
                                                     'Current.Export',
                                                     'Current.Offered',
                                                     'Voltage',
                                                     'Frequency',
                                                     'Temperature',
                                                     'SoC',
                                                     'RPM'],
                                            'type': 'string'},
                              'phase': {'additionalProperties': False,
                                        'enum': ['L1',
                                                 'L2',
                                                 'L3',
                                                 'N',
                                                 'L1-N',
                                                 'L2-N',
                                                 'L3-N',
                                                 'L1-L2',
                                                 'L2-L3',
                                                 'L3-L1'],
                                        'type': 'string'},
                              'unit': {'additionalProperties': False,
                                       'enum': ['Wh',
                                                'kWh',
                                                'varh',
                                                'kvarh',
                                                'W',
                                                'kW',
                                                'VA',
                                                'kVA',
                                                'var',
                                                'kvar',
                                                'A',
                                                'V',
                                                'K',
                                                'Celcius',
                                                'Celsius',
                                                'Fahrenheit',
                                                'Percent',
                                                'Hertz'],
                                       'type': 'string'},
                              'value': {'type': 'string'}},
               'required': ['value'],
               'type': 'object'},
     'minItems': 1,
     'type': 'array'}

On instance['meterValue'][0]['sampledValue']:
    []

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/config/custom_components/ocpp/api.py", line 898, in run
    await asyncio.gather(*self.tasks)
  File "/usr/local/lib/python3.9/site-packages/ocpp/charge_point.py", line 131, in start
    await self.route_message(message)
  File "/usr/local/lib/python3.9/site-packages/ocpp/charge_point.py", line 150, in route_message
    await self._handle_call(msg)
  File "/config/custom_components/ocpp/api.py", line 883, in _handle_call
    await super()._handle_call(msg)
  File "/usr/local/lib/python3.9/site-packages/ocpp/charge_point.py", line 178, in _handle_call
    validate_payload(msg, self._ocpp_version)
  File "/usr/local/lib/python3.9/site-packages/ocpp/messages.py", line 204, in validate_payload
    raise ValidationError(f"Payload '{message.payload} for action "
ocpp.exceptions.ValidationError: Payload '{'connectorId': 1, 'meterValue': [{'timestamp': '2022-03-29T19:15:00Z', 'sampledValue': []}]} for action 'MeterValues' is not valid: [] is too short

Failed validating 'minItems' in schema['properties']['meterValue']['items']['properties']['sampledValue']:
    {'items': {'additionalProperties': False,
               'properties': {'context': {'additionalProperties': False,
                                          'enum': ['Interruption.Begin',
                                                   'Interruption.End',
                                                   'Sample.Clock',
                                                   'Sample.Periodic',
                                                   'Transaction.Begin',
                                                   'Transaction.End',
                                                   'Trigger',
                                                   'Other'],
                                          'type': 'string'},
                              'format': {'additionalProperties': False,
                                         'enum': ['Raw', 'SignedData'],
                                         'type': 'string'},
                              'location': {'additionalProperties': False,
                                           'enum': ['Cable',
                                                    'EV',
                                                    'Inlet',
                                                    'Outlet',
                                                    'Body'],
                                           'type': 'string'},
                              'measurand': {'additionalProperties': False,
                                            'enum': ['Energy.Active.Export.Register',
                                                     'Energy.Active.Import.Register',
                                                     'Energy.Reactive.Export.Register',
                                                     'Energy.Reactive.Import.Register',
                                                     'Energy.Active.Export.Interval',
                                                     'Energy.Active.Import.Interval',
                                                     'Energy.Reactive.Export.Interval',
                                                     'Energy.Reactive.Import.Interval',
                                                     'Power.Active.Export',
                                                     'Power.Active.Import',
                                                     'Power.Offered',
                                                     'Power.Reactive.Export',
                                                     'Power.Reactive.Import',
                                                     'Power.Factor',
                                                     'Current.Import',
                                                     'Current.Export',
                                                     'Current.Offered',
                                                     'Voltage',
                                                     'Frequency',
                                                     'Temperature',
                                                     'SoC',
                                                     'RPM'],
                                            'type': 'string'},
                              'phase': {'additionalProperties': False,
                                        'enum': ['L1',
                                                 'L2',
                                                 'L3',
                                                 'N',
                                                 'L1-N',
                                                 'L2-N',
                                                 'L3-N',
                                                 'L1-L2',
                                                 'L2-L3',
                                                 'L3-L1'],
                                        'type': 'string'},
                              'unit': {'additionalProperties': False,
                                       'enum': ['Wh',
                                                'kWh',
                                                'varh',
                                                'kvarh',
                                                'W',
                                                'kW',
                                                'VA',
                                                'kVA',
                                                'var',
                                                'kvar',
                                                'A',
                                                'V',
                                                'K',
                                                'Celcius',
                                                'Celsius',
                                                'Fahrenheit',
                                                'Percent',
                                                'Hertz'],
                                       'type': 'string'},
                              'value': {'type': 'string'}},
               'required': ['value'],
               'type': 'object'},
     'minItems': 1,
     'type': 'array'}

On instance['meterValue'][0]['sampledValue']:
    []
2022-03-29 21:15:37 INFO (MainThread) [ocpp] Garage: receive message [2,"31ba3d0e-83c6-439a-9e07-05722ea9d9cd","BootNotification",{
    "chargePointModel": "EVC04",
    "chargePointVendor": "VESTEL",
    "chargePointSerialNumber": "7000167921000005",
    "firmwareVersion": "v3.43.0-1.0.88.0",
    "meterType": "internal",
    "chargeBoxSerialNumber": "7000167921000005"
    }]
2022-03-29 21:15:37 INFO (MainThread) [ocpp] Garage: send [3,"31ba3d0e-83c6-439a-9e07-05722ea9d9cd",{"currentTime":"2022-03-29T19:15:37.204038+00:00","interval":3600,"status":"Accepted"}]
2022-03-29 21:15:38 INFO (MainThread) [ocpp] Garage: receive message [2,"a37bc000-0cf4-4523-8bb0-d389c7d49c4e","Heartbeat",{}]
2022-03-29 21:15:38 INFO (MainThread) [ocpp] Garage: send [3,"a37bc000-0cf4-4523-8bb0-d389c7d49c4e",{"currentTime":"2022-03-29T19:15:38.309581+00:00"}]
2022-03-29 21:15:39 INFO (MainThread) [ocpp] Garage: send [2,"18123233-894c-4dc1-8581-37c74eaa5f17","GetConfiguration",{"key":["SupportedFeatureProfiles"]}]
2022-03-29 21:15:39 INFO (MainThread) [ocpp] Garage: receive message [3,"18123233-894c-4dc1-8581-37c74eaa5f17",{
    "configurationKey": [
        {
            "key": "SupportedFeatureProfiles",
            "readonly": true,
            "value": "Core,FirmwareManagement,LocalAuthListManagement,Reservation,SmartCharging,RemoteTrigger"
        }
    ]
    }]
2022-03-29 21:15:39 INFO (MainThread) [ocpp] Garage: send [2,"6276a2c1-eaf2-45b8-9809-fb689d343b43","GetConfiguration",{"key":["NumberOfConnectors"]}]
2022-03-29 21:15:39 INFO (MainThread) [ocpp] Garage: receive message [3,"6276a2c1-eaf2-45b8-9809-fb689d343b43",{
    "configurationKey": [
        {
            "key": "NumberOfConnectors",
            "readonly": true,
            "value": "1"
        }
    ]
    }]
2022-03-29 21:15:39 INFO (MainThread) [ocpp] Garage: send [2,"7e3684b0-d303-4489-9658-3f845c82085e","ChangeAvailability",{"connectorId":0,"type":"Operative"}]
2022-03-29 21:15:39 INFO (MainThread) [ocpp] Garage: receive message [3,"7e3684b0-d303-4489-9658-3f845c82085e",{"status":"Accepted"}]
2022-03-29 21:15:39 INFO (MainThread) [ocpp] Garage: send [2,"ec49c10f-a36b-4be1-a6d6-77a94ff85054","GetConfiguration",{"key":["HeartbeatInterval"]}]
2022-03-29 21:15:39 INFO (MainThread) [ocpp] Garage: receive message [2,"e2a4dc8a-77e2-4156-aba3-98ddca2b0060","StatusNotification",{"connectorId":0,"errorCode":"NoError","status":"Available","timestamp":"2022-03-29T19:15:38Z"}]
2022-03-29 21:15:39 INFO (MainThread) [ocpp] Garage: send [3,"e2a4dc8a-77e2-4156-aba3-98ddca2b0060",{}]

```

**Comment by N3rdix** [comment]
I was able to eliminate at least one persistent notification for the rejected MeterValuesSampledData by adjusting the values in the charger settings.
But the integration still reports a "charger <XXX> rebooted" every 10 minutes with the log messages from my previous post

**Comment by lbbrhzn** [comment]
The MeterValues.req that is sent by the new firmare does not comply to the OCPP standard. There should be at least one SampledValue in a MeterValue record, but your chargers sends a message with no MeterValue. You can try to enable the skip ocpp validation in the configuration flow.

The charger rebooted message occurs when an untriggered boot notification is  received, presumably because the charger rebooted due to an internal error.

Looks like the new firmware is not really an improvement. I would recommend to switch back to the previous version.

**Comment by drc38** [comment]
You could also try setting Idle Interval to 0 so that the charger only reports meterValues when it is charging.

**Comment by N3rdix** [comment]
> The MeterValues.req that is sent by the new firmare does not comply to the OCPP standard. There should be at least one SampledValue in a MeterValue record, but your chargers sends a message with no MeterValue. You can try to enable the skip ocpp validation in the configuration flow.
> 
> The charger rebooted message occurs when an untriggered boot notification is received, presumably because the charger rebooted due to an internal error.
> 
> Looks like the new firmware is not really an improvement. I would recommend to switch back to the previous version.

Thanks for clarifying that, I will try to contact Vestel and tell them the story, maybe they are motivated enough to fix the bug in a future firmware update.

Unfortunately I cannot roll back to an older firmware version as this one got pushed OTA :-(

I will give @drc38 's proposal a chance and see what happens.

**Comment by N3rdix** [comment]
@drc38 your proposal works as expected, no more errors in idle mode. 

I've reported this issue to the manufacturer Vestel and they will hopefully fix it with an upcoming update.
