### ISSUE TITLE
Error in connection handler

### ISSUE THREAD

**Issue by jeremycoppey** [lbbrhzn/ocpp#5]
Hello,
I just installed your custom component:
HA: core-2021.4.6
HACS: 1.12.3
My wallbox: EVlink schneider electric, OCPP 1.6

Error log:
```
Logger: websockets.server
Source: custom_components/ocpp/sensor.py:276
First occurred: 1:43:14 AM (2 occurrences)
Last logged: 1:57:19 AM

Error in connection handler
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/site-packages/websockets/protocol.py", line 827, in transfer_data
    message = await self.read_message()
  File "/usr/local/lib/python3.8/site-packages/websockets/protocol.py", line 895, in read_message
    frame = await self.read_data_frame(max_size=self.max_size)
  File "/usr/local/lib/python3.8/site-packages/websockets/protocol.py", line 971, in read_data_frame
    frame = await self.read_frame(max_size)
  File "/usr/local/lib/python3.8/site-packages/websockets/protocol.py", line 1047, in read_frame
    frame = await Frame.read(
  File "/usr/local/lib/python3.8/site-packages/websockets/framing.py", line 105, in read
    data = await reader(2)
  File "/usr/local/lib/python3.8/asyncio/streams.py", line 723, in readexactly
    await self._wait_for_data('readexactly')
  File "/usr/local/lib/python3.8/asyncio/streams.py", line 517, in _wait_for_data
    await self._waiter
asyncio.exceptions.CancelledError

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/usr/local/lib/python3.8/site-packages/websockets/server.py", line 191, in handler
    await self.ws_handler(self, path)
  File "/config/custom_components/ocpp/sensor.py", line 110, in on_connect
    await cp.start()
  File "/config/custom_components/ocpp/sensor.py", line 276, in start
    await asyncio.gather(super().start(), self.post_connect())
  File "/usr/local/lib/python3.8/site-packages/ocpp/charge_point.py", line 123, in start
    message = await self._connection.recv()
  File "/usr/local/lib/python3.8/site-packages/websockets/protocol.py", line 509, in recv
    await self.ensure_open()
  File "/usr/local/lib/python3.8/site-packages/websockets/protocol.py", line 812, in ensure_open
    raise self.connection_closed_exc()
websockets.exceptions.ConnectionClosedError: code = 1006 (connection closed abnormally [internal]), no reason
```
The only working sensors in my setup is the status and the heartbeat.

![image](https://user-images.githubusercontent.com/13691266/116798060-57faf380-aaec-11eb-9912-05cf7cafae9d.png)

**Comment by drc38** [comment]
This should also be resolved through reconnecting rather than initiating a new charge point instance. Approach can probably be improved on though.
