### ISSUE TITLE
Integration crashes frequently: websockets.exceptions.ConnectionClosedError

### ISSUE THREAD

**Issue by FloThinksPi** [lbbrhzn/ocpp#656]
**Describe the bug**
Since updating to 0.4.35 from quite an old version i see frequent restarts of the integration (800 times per day roughly).
Any ideas on this, it could also be the Charger having a flaky OCCP implementation yet it worked with older version of the integration without a crash.
Maybe this just needs catching and ignoring the exception since the integration seems to work fine except this uncaught exception leading to a crash. In case of a unexpected connection close (which also can be network related) the code should just retry establishing the connection i guess instead of exiting. Not looked deep into the integrations code yet but thats my assumption on the trackback below.

**To Reproduce**
Dont know exactly, happens randomly and causes random restarts of the integration.

**Expected behavior**
OCPP Integration does not creash/restart

**Actual behavior**

There are following tracebacks when the integration crashes.
A restart is logged in HAs notifications for every such event.

```
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/site-packages/websockets/legacy/protocol.py", line 945, in transfer_data
    message = await self.read_message()
  File "/usr/local/lib/python3.10/site-packages/websockets/legacy/protocol.py", line 1015, in read_message
    frame = await self.read_data_frame(max_size=self.max_size)
  File "/usr/local/lib/python3.10/site-packages/websockets/legacy/protocol.py", line 1090, in read_data_frame
    frame = await self.read_frame(max_size)
  File "/usr/local/lib/python3.10/site-packages/websockets/legacy/protocol.py", line 1145, in read_frame
    frame = await Frame.read(
  File "/usr/local/lib/python3.10/site-packages/websockets/legacy/framing.py", line 70, in read
    data = await reader(2)
  File "/usr/local/lib/python3.10/asyncio/streams.py", line 706, in readexactly
    raise exceptions.IncompleteReadError(incomplete, n)
asyncio.exceptions.IncompleteReadError: 0 bytes read on a total of 2 expected bytes

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/config/custom_components/ocpp/api.py", line 411, in post_connect
    await self.get_supported_features()
  File "/config/custom_components/ocpp/api.py", line 485, in get_supported_features
    resp = await self.call(req)
  File "/usr/local/lib/python3.10/site-packages/ocpp/charge_point.py", line 271, in call
    await self._send(call.to_json())
  File "/usr/local/lib/python3.10/site-packages/ocpp/charge_point.py", line 325, in _send
    await self._connection.send(message)
  File "/usr/local/lib/python3.10/site-packages/websockets/legacy/protocol.py", line 620, in send
    await self.ensure_open()
  File "/usr/local/lib/python3.10/site-packages/websockets/legacy/protocol.py", line 921, in ensure_open
    raise self.connection_closed_exc()
websockets.exceptions.ConnectionClosedError: no close frame received or sent
```
**Additional Info**

Communication partner is a `EVC04-AC11` charger. OCCP 1.6.

**Comment by FloThinksPi** [comment]
Ah reading the logs again this might not be the integration that's restarting (maybe also) but rather the Charger itself, is this the case ?

**Comment by N3rdix** [comment]
Haven’t updated yet, still on 0.4.33 with my EVC04-AC22 without issues.
Can you check with logger set to debug in home assistant?

It could also help to download the logs from the wallboard web interface.

out of curiosity, which firmware version do you have? I reported a violation to Vestel on the OCPP standard and they provided a fix recently which might not be public yet (v3.50.0)

**Comment by FloThinksPi** [comment]
@N3rdix the version i got on the Wallbox is `v3.57.0-1.0.108.0`.
Trying yo get some debug logs :)

**Comment by FloThinksPi** [comment]
Looks like this call
```
2022-10-25 05:10:40.512 INFO (MainThread) [ocpp] central: send [2,"GUID","GetConfiguration",{"key":["SupportedFeatureProfiles"]}]
```
Crashes the charger so not an issue with the integration
```
2022-10-25 05:11:55.240 DEBUG (MainThread) [custom_components.ocpp] Received boot notification for central: {'charge_point_model': 'EVC04', 'charge_point_vendor': 'VESTEL', 'charge_point_serial_number': 'xxx', 'firmware_version': 'v3.57.0-1.0.108.0', 'meter_type': 'internal', 'charge_box_serial_number': 'xxx'}
```
Guess i need to reach out to Vestel support :/ 
Whats funny is, the above `SupportedFeatureProfiles` call works except between 5:00 and 6:00. In this timespan it reboots the charger. After 6:00 it works again.

**Comment by duckfullstop** [comment]
Interestingly, a CP crash has started happening to me (i.e CP reboots with an associated `ConnectionClosedError`) after upgrading my ABB Terra AC to the latest firmware version (v1.6.5), which seems to be triggering this erorr.

Reading through my logs it seems that everything seems perfectly in order up until that query, so I'm kind of perplexed. Downgrading to the last firmware release works fine. I wonder whether there's a quirk in the codebase here to work around some kind of non-standard behaviour that's causing a regression, making this more than initially meets the eye?

v1.6.5 logs:
```
2022-11-11 21:22:01.943 INFO (MainThread) [websockets.server] connection open
2022-11-11 21:22:01.943 INFO (MainThread) [custom_components.ocpp] Websocket Subprotocol matched: ocpp1.6
2022-11-11 21:22:01.943 INFO (MainThread) [custom_components.ocpp] Charger websocket path=/TACWREDACTED
2022-11-11 21:22:01.943 INFO (MainThread) [custom_components.ocpp] Charger TACWREDACTED connected to 0.0.0.0:12811.
2022-11-11 21:22:02.808 INFO (MainThread) [ocpp] TACWREDACTED: receive message [2, "4289088", "BootNotification", {"chargePointModel": "CDT_TACW7::NET_ETH", "chargePointVendor": "ABB", "chargeBoxSerialNumber": "TACWREDACTED", "firmwareVersion": "TAC1Z9118606710247::V1.6.5", "meterType": "V1"}]
2022-11-11 21:22:02.812 INFO (MainThread) [ocpp] TACWREDACTED: send [3,"4289088",{"currentTime":"2022-11-11T21:22:02Z","interval":3600,"status":"Accepted"}]
2022-11-11 21:22:02.819 WARNING (MainThread) [homeassistant.helpers.entity_component] Forced update failed. Entity sensor.charger_connection_latency not found.
2022-11-11 21:22:03.302 INFO (MainThread) [ocpp] TACWREDACTED: receive message [2, "9274563", "StatusNotification", {"connectorId": 0, "errorCode": "NoError", "info": "null", "status": "Available", "vendorErrorCode": "0x0000"}]
2022-11-11 21:22:03.307 INFO (MainThread) [ocpp] TACWREDACTED: send [3,"9274563",{}]
2022-11-11 21:22:03.312 WARNING (MainThread) [homeassistant.helpers.entity_component] Forced update failed. Entity sensor.charger_connection_latency not found.
2022-11-11 21:22:03.953 INFO (MainThread) [ocpp] TACWREDACTED: send [2,"46719f1b-dc2b-4a50-acb1-b9058751ed8b","GetConfiguration",{"key":["SupportedFeatureProfiles"]}]
2022-11-11 21:22:14.272 INFO (MainThread) [custom_components.ocpp] Charger TACWREDACTED disconnected from 0.0.0.0:12811.
2022-11-11 21:22:14.273 INFO (MainThread) [ocpp] TACWREDACTED: send [2,"9386ed18-6222-4775-abea-a0c8296e86ad","GetConfiguration",{"key":["SupportedFeatureProfiles"]}]
2022-11-11 21:22:14.273 ERROR (MainThread) [homeassistant] Error doing job: Task exception was never retrieved
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/site-packages/websockets/legacy/protocol.py", line 968, in transfer_data
    message = await self.read_message()
  File "/usr/local/lib/python3.10/site-packages/websockets/legacy/protocol.py", line 1038, in read_message
    frame = await self.read_data_frame(max_size=self.max_size)
  File "/usr/local/lib/python3.10/site-packages/websockets/legacy/protocol.py", line 1113, in read_data_frame
    frame = await self.read_frame(max_size)
  File "/usr/local/lib/python3.10/site-packages/websockets/legacy/protocol.py", line 1170, in read_frame
    frame = await Frame.read(
  File "/usr/local/lib/python3.10/site-packages/websockets/legacy/framing.py", line 69, in read
    data = await reader(2)
  File "/usr/local/lib/python3.10/asyncio/streams.py", line 706, in readexactly
    raise exceptions.IncompleteReadError(incomplete, n)
asyncio.exceptions.IncompleteReadError: 0 bytes read on a total of 2 expected bytes

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/config/custom_components/ocpp/api.py", line 411, in post_connect
    await self.get_supported_features()
  File "/config/custom_components/ocpp/api.py", line 485, in get_supported_features
    resp = await self.call(req)
  File "/config/deps/lib/python3.10/site-packages/ocpp/charge_point.py", line 271, in call
    await self._send(call.to_json())
  File "/config/deps/lib/python3.10/site-packages/ocpp/charge_point.py", line 325, in _send
    await self._connection.send(message)
  File "/usr/local/lib/python3.10/site-packages/websockets/legacy/protocol.py", line 635, in send
    await self.ensure_open()
  File "/usr/local/lib/python3.10/site-packages/websockets/legacy/protocol.py", line 944, in ensure_open
    raise self.connection_closed_exc()
websockets.exceptions.ConnectionClosedError: no close frame received or sent
2022-11-11 21:22:14.287 INFO (MainThread) [websockets.server] connection closed
```

v1.5.2 logs:
```
2022-11-11 21:31:15.239 INFO (MainThread) [websockets.server] connection open
2022-11-11 21:31:15.239 INFO (MainThread) [custom_components.ocpp] Websocket Subprotocol matched: ocpp1.6
2022-11-11 21:31:15.239 INFO (MainThread) [custom_components.ocpp] Charger websocket path=/TACWREDACTED
2022-11-11 21:31:15.239 INFO (MainThread) [custom_components.ocpp] Charger TACWREDACTED reconnected to 0.0.0.0:12811.
2022-11-11 21:31:15.439 INFO (MainThread) [ocpp] TACWREDACTED: receive message [2, "4289088", "BootNotification", {"chargePointModel": "CDT_TACW7::NET_ETH", "chargePointVendor": "Chargedot", "chargeBoxSerialNumber": "TACWREDACTED", "firmwareVersion": "TAC1Z9118606710247::V1.5.2", "meterType": "V1"}]
2022-11-11 21:31:15.440 INFO (MainThread) [ocpp] TACWREDACTED: send [3,"4289088",{"currentTime":"2022-11-11T21:31:15Z","interval":3600,"status":"Accepted"}]
2022-11-11 21:31:15.447 WARNING (MainThread) [homeassistant.helpers.entity_component] Forced update failed. Entity sensor.charger_connection_latency not found.
2022-11-11 21:31:15.939 INFO (MainThread) [ocpp] TACWREDACTED: receive message [2, "9274563", "StatusNotification", {"connectorId": 0, "errorCode": "NoError", "info": "null", "status": "Available", "vendorErrorCode": "0x00"}]
2022-11-11 21:31:15.939 INFO (MainThread) [ocpp] TACWREDACTED: send [3,"9274563",{}]
2022-11-11 21:31:15.942 WARNING (MainThread) [homeassistant.helpers.entity_component] Forced update failed. Entity sensor.charger_connection_latency not found.
2022-11-11 21:31:16.439 INFO (MainThread) [ocpp] TACWREDACTED: receive message [2, "5706945", "StatusNotification", {"connectorId": 1, "errorCode": "NoError", "info": "null", "status": "Available", "vendorErrorCode": "0x00"}]
2022-11-11 21:31:16.439 INFO (MainThread) [ocpp] TACWREDACTED: send [3,"5706945",{}]
2022-11-11 21:31:16.444 WARNING (MainThread) [homeassistant.helpers.entity_component] Forced update failed. Entity sensor.charger_connection_latency not found.
2022-11-11 21:31:17.241 INFO (MainThread) [ocpp] TACWREDACTED: send [2,"ccb1de07-71f8-4326-9ab2-95c72d5432f1","GetConfiguration",{"key":["SupportedFeatureProfiles"]}]
2022-11-11 21:31:17.244 INFO (MainThread) [ocpp] TACWREDACTED: receive message [3, "ccb1de07-71f8-4326-9ab2-95c72d5432f1", {"configurationKey": [{"key": "SupportedFeatureProfiles", "readonly": true, "value": "Core,FirmwareManagement,LocalAuthListManagement,RemoteTrigger"}], "unknownKey": []}]
2022-11-11 21:31:17.250 INFO (MainThread) [ocpp] TACWREDACTED: send [2,"eaffa2a8-db73-4b10-830e-360661589d6e","GetConfiguration",{"key":["NumberOfConnectors"]}]
2022-11-11 21:31:17.744 INFO (MainThread) [ocpp] TACWREDACTED: receive message [3, "eaffa2a8-db73-4b10-830e-360661589d6e", {"configurationKey": [{"key": "NumberOfConnectors", "readonly": true, "value": "1"}], "unknownKey": []}]
2022-11-11 21:31:17.744 INFO (MainThread) [ocpp] TACWREDACTED: send [2,"caba5e05-f7ef-4216-8ae1-0baa8fd1030b","GetConfiguration",{"key":["SupportedFeatureProfiles"]}]
2022-11-11 21:31:18.245 INFO (MainThread) [ocpp] TACWREDACTED: receive message [3, "caba5e05-f7ef-4216-8ae1-0baa8fd1030b", {"configurationKey": [{"key": "SupportedFeatureProfiles", "readonly": true, "value": "Core,FirmwareManagement,LocalAuthListManagement,RemoteTrigger"}], "unknownKey": []}]
2022-11-11 21:31:18.246 INFO (MainThread) [ocpp] TACWREDACTED: send [2,"a51cb886-8b26-4bc9-a31e-191cfd136f70","GetConfiguration",{"key":["HeartbeatInterval"]}]
2022-11-11 21:31:18.746 INFO (MainThread) [ocpp] TACWREDACTED: receive message [3, "a51cb886-8b26-4bc9-a31e-191cfd136f70", {"configurationKey": [{"key": "HeartbeatInterval", "readonly": false, "value": "3600"}], "unknownKey": []}]
2022-11-11 21:31:18.746 INFO (MainThread) [ocpp] TACWREDACTED: send [2,"6325e9c8-7d0c-4518-ad99-98a0c70b8e03","GetConfiguration",{"key":["NumberOfConnectors"]}]
2022-11-11 21:31:19.243 INFO (MainThread) [ocpp] TACWREDACTED: receive message [3, "6325e9c8-7d0c-4518-ad99-98a0c70b8e03", {"configurationKey": [{"key": "NumberOfConnectors", "readonly": true, "value": "1"}], "unknownKey": []}]
2022-11-11 21:31:19.244 INFO (MainThread) [ocpp] TACWREDACTED: send [2,"da997cac-7018-4071-8af8-6cfa21090b3e","GetConfiguration",{"key":["MeterValuesSampledData"]}]
2022-11-11 21:31:19.744 INFO (MainThread) [ocpp] TACWREDACTED: receive message [3, "da997cac-7018-4071-8af8-6cfa21090b3e", {"configurationKey": [], "unknownKey": ["MeterValuesSampledData"]}]
```

**Comment by drc38** [comment]
Sounds like there are issues with the latest ABB firmware see #684

**Comment by duckfullstop** [comment]
Well noted, will move this discussion to here - though I wonder if this issue is directly correlated / needs reopening as a result?
