### ISSUE TITLE
Integration crashing while communicating with Weidmüller Business (Wallbe backend) 

### ISSUE THREAD

**Issue by linuxstony** [lbbrhzn/ocpp#716]
**Describe the bug**
I am able to connect the Wallbox with your integration just fine - the values are beeing displayed  - then after a few seconds the integration seems to crash and to reboot. 

**To Reproduce**
Hard to tell.
**Expected behavior**
No crashes :)

**Screenshots**
![ksnip_20221218-162056](https://user-images.githubusercontent.com/10862262/208306741-dfc06a21-159b-4a20-b0f7-55b4ae14a401.png)
![ksnip_20221218-162119](https://user-images.githubusercontent.com/10862262/208306746-184afeb8-2972-48a0-a85b-9560a71f2724.png)
![ksnip_20221218-162132](https://user-images.githubusercontent.com/10862262/208306750-60a1370e-fb85-4c0b-869e-665349c7088b.png)

**Additional context**

The Wallbox uses a Wallbe-Backend which claims to be OCPP 1.6 compatible "

A part of the logfile:

2022-12-18 12:58:27.446 ERROR (MainThread) [custom_components.ocpp] Unexpected exception in connection to '': 'argument of type 'int' is not iterable'
Traceback (most recent call last):
  File "/config/custom_components/ocpp/api.py", line 920, in run
    await asyncio.gather(*self.tasks)
  File "/config/custom_components/ocpp/api.py", line 451, in post_connect
    if prof.SMART in self._attr_supported_features:
TypeError: argument of type 'int' is not iterable
2022-12-18 12:58:27.496 INFO (MainThread) [ocpp] : receive message [3,"e9a5be5f-734e-4b9d-bd68-5c07375afb33",{"status":"Rejected"}]
2022-12-18 12:58:27.499 WARNING (MainThread) [custom_components.ocpp] Rejected while setting MeterValuesSampledData to Energy.Active.Import.Register,Energy.Reactive.Import.Register,Energy.Active.Import.Interval,Energy.Reactive.Import.Interval,Power.Active.Import,Power.Reactive.Import,Power.Offered,Power.Factor,Current.Import,Current.Offered,Voltage,Frequency,SoC,Temperature
2022-12-18 12:58:27.509 INFO (MainThread) [ocpp] : send [2,"d2b65ea1-d04d-47a6-92c6-95ba134c85d5","GetConfiguration",{"key":["MeterValueSampleInterval"]}]
2022-12-18 12:58:27.618 ERROR (MainThread) [homeassistant] Error doing job: Task exception was never retrieved
Traceback (most recent call last):
  File "/config/custom_components/ocpp/api.py", line 419, in post_connect
    await self.configure(
  File "/config/custom_components/ocpp/api.py", line 813, in configure
    resp = await self.call(req)
  File "/usr/local/lib/python3.10/site-packages/ocpp/charge_point.py", line 271, in call
    await self._send(call.to_json())
  File "/usr/local/lib/python3.10/site-packages/ocpp/charge_point.py", line 325, in _send
    await self._connection.send(message)
  File "/usr/local/lib/python3.10/site-packages/websockets/legacy/protocol.py", line 635, in send
    await self.ensure_open()
  File "/usr/local/lib/python3.10/site-packages/websockets/legacy/protocol.py", line 953, in ensure_open
    raise self.connection_closed_exc()
websockets.exceptions.ConnectionClosedOK: sent 1000 (OK); then received 1000 (OK)
2022-12-18 12:58:29.045 WARNING (MainThread) [homeassistant.components.camera] Updating xiaomi_cloud_map_extractor camera took longer than the scheduled update interval 0:00:05
2022-12-18 12:58:34.047 WARNING (MainThread) [homeassistant.components.camera] Updating xiaomi_cloud_map_extractor camera took longer than the scheduled update interval 0:00:05
2022-12-18 12:58:39.054 WARNING (MainThread) [homeassistant.components.camera] Updating xiaomi_cloud_map_extractor camera took longer than the scheduled update interval 0:00:05
2022-12-18 12:58:49.065 WARNING (MainThread) [homeassistant.components.camera] Updating xiaomi_cloud_map_extractor camera took longer than the scheduled update interval 0:00:05
2022-12-18 12:59:19.080 WARNING (MainThread) [homeassistant.components.camera] Updating xiaomi_cloud_map_extractor camera took longer than the scheduled update interval 0:00:05
2022-12-18 12:59:24.081 WARNING (MainThread) [homeassistant.helpers.entity] Update of camera.xiaomi_cloud_map_extractor is taking over 10 seconds
2022-12-18 12:59:24.084 WARNING (MainThread) [homeassistant.components.camera] Updating xiaomi_cloud_map_extractor camera took longer than the scheduled update interval 0:00:05
2022-12-18 12:59:24.252 WARNING (SyncWorker_0) [custom_components.xiaomi_cloud_map_extractor.camera] Unable to retrieve map data
2022-12-18 12:59:28.238 INFO (MainThread) [ocpp] : receive message [2,"16","BootNotification",{"chargePointVendor":"wallbe","chargePointModel":"Smart Charge Control","chargePointSerialNumber":"00000000596","firmwareVersion":"BF-01.04.13"}]
2022-12-18 12:59:28.242 INFO (MainThread) [ocpp] : send [3,"16",{"currentTime":"2022-12-18T12:59:28Z","interval":3600,"status":"Accepted"}]
2022-12-18 12:59:28.561 INFO (MainThread) [ocpp] : receive message [2,"17","StatusNotification",{"connectorId":0,"errorCode":"NoError","status":"Available","vendorErrorCode":"0","timestamp":"2022-12-18T12:59:28.002Z"}]
2022-12-18 12:59:28.566 INFO (MainThread) [ocpp] : send [3,"17",{}]
2022-12-18 12:59:28.688 INFO (MainThread) [ocpp] : receive message [2,"18","StatusNotification",{"connectorId":1,"errorCode":"NoError","status":"Preparing","vendorErrorCode":"0","timestamp":"2022-12-18T12:59:28.003Z"}]
2022-12-18 12:59:28.692 INFO (MainThread) [ocpp] : send [3,"18",{}]
2022-12-18 12:59:29.966 INFO (MainThread) [ocpp] : send [2,"78f2bb8c-c5b8-4f00-bc68-bbcb0c354b3c","GetConfiguration",{"key":["SupportedFeatureProfiles"]}]
2022-12-18 12:59:30.032 INFO (MainThread) [ocpp] : receive message [3,"78f2bb8c-c5b8-4f00-bc68-bbcb0c354b3c",{"configurationKey":[{"key":"SupportedFeatureProfiles","readonly":true,"value":"true"}],"unknownKey":[]}]
2022-12-18 12:59:30.034 WARNING (MainThread) [custom_components.ocpp] Unknown feature profile detected ignoring: true
2022-12-18 12:59:30.037 INFO (MainThread) [ocpp] : send [2,"a3fb4c6e-d0ad-41af-82b9-4ea3c7124737","GetConfiguration",{"key":["NumberOfConnectors"]}]
2022-12-18 12:59:30.107 INFO (MainThread) [ocpp] : receive message [3,"a3fb4c6e-d0ad-41af-82b9-4ea3c7124737",{"configurationKey":[{"key":"NumberOfConnectors","readonly":true,"value":"1"}],"unknownKey":[]}]
2022-12-18 12:59:30.110 INFO (MainThread) [ocpp] : send [2,"51ec4307-76e1-42d5-8296-083740551d1a","GetConfiguration",{"key":["HeartbeatInterval"]}]
2022-12-18 12:59:30.237 INFO (MainThread) [ocpp] : receive message [3,"51ec4307-76e1-42d5-8296-083740551d1a",{"configurationKey":[{"key":"HeartbeatInterval","readonly":false,"value":"3600"}],"unknownKey":[]}]
2022-12-18 12:59:30.245 INFO (MainThread) [ocpp] : send [2,"728dd2d7-8912-4356-ad74-025887f59bf4","GetConfiguration",{"key":["MeterValuesSampledData"]}]
2022-12-18 12:59:30.363 INFO (MainThread) [ocpp] : receive message [3,"728dd2d7-8912-4356-ad74-025887f59bf4",{"configurationKey":[{"key":"MeterValuesSampledData","readonly":true,"value":"true"}],"unknownKey":[]}]
2022-12-18 12:59:30.369 WARNING (MainThread) [custom_components.ocpp] MeterValuesSampledData is a read only setting
2022-12-18 12:59:30.376 INFO (MainThread) [ocpp] : send [2,"e6ab4db5-adb5-40c6-814a-03677678dc27","GetConfiguration",{"key":["SupportedFeatureProfiles"]}]
2022-12-18 12:59:30.437 INFO (MainThread) [ocpp] : receive message [3,"e6ab4db5-adb5-40c6-814a-03677678dc27",{"configurationKey":[{"key":"SupportedFeatureProfiles","readonly":true,"value":"true"}],"unknownKey":[]}]
2022-12-18 12:59:30.442 WARNING (MainThread) [custom_components.ocpp] Unknown feature profile detected ignoring: true
2022-12-18 12:59:30.450 INFO (MainThread) [ocpp] : send [2,"02de4bbf-abd0-4a77-91ee-c950f7c84959","ChangeConfiguration",{"key":"MeterValuesSampledData","value":"Energy.Active.Import.Register,Energy.Reactive.Import.Register,Energy.Active.Import.Interval,Energy.Reactive.Import.Interval,Power.Active.Import,Power.Reactive.Import,Power.Offered,Power.Factor,Current.Import,Current.Offered,Voltage,Frequency,SoC,Temperature"}]
2022-12-18 12:59:30.570 INFO (MainThread) [ocpp] : receive message [3,"02de4bbf-abd0-4a77-91ee-c950f7c84959",{"status":"Rejected"}]
2022-12-18 12:59:30.573 WARNING (MainThread) [custom_components.ocpp] Rejected while setting MeterValuesSampledData to Energy.Active.Import.Register,Energy.Reactive.Import.Register,Energy.Active.Import.Interval,Energy.Reactive.Import.Interval,Power.Active.Import,Power.Reactive.Import,Power.Offered,Power.Factor,Current.Import,Current.Offered,Voltage,Frequency,SoC,Temperature
2022-12-18 12:59:30.588 INFO (MainThread) [ocpp] : send [2,"04a5408d-eed5-4fd2-ae07-8c294a9e9368","GetConfiguration",{"key":["NumberOfConnectors"]}]
2022-12-18 12:59:30.694 INFO (MainThread) [ocpp] : receive message [3,"04a5408d-eed5-4fd2-ae07-8c294a9e9368",{"configurationKey":[{"key":"NumberOfConnectors","readonly":true,"value":"1"}],"unknownKey":[]}]
2022-12-18 12:59:30.696 INFO (MainThread) [ocpp] : send [2,"97159642-3e36-4ddd-bd07-3a05bb028249","GetConfiguration",{"key":["MeterValueSampleInterval"]}]
2022-12-18 12:59:30.770 INFO (MainThread) [ocpp] : receive message [3,"97159642-3e36-4ddd-bd07-3a05bb028249",{"configurationKey":[{"key":"MeterValueSampleInterval","readonly":false,"value":"60"}],"unknownKey":[]}]
2022-12-18 12:59:30.772 INFO (MainThread) [ocpp] : send [2,"5ec69f3c-c1a6-423d-9a1d-83bd50d34776","GetConfiguration",{"key":["HeartbeatInterval"]}]
2022-12-18 12:59:30.898 INFO (MainThread) [ocpp] : receive message [3,"5ec69f3c-c1a6-423d-9a1d-83bd50d34776",{"configurationKey":[{"key":"HeartbeatInterval","readonly":false,"value":"3600"}],"unknownKey":[]}]
2022-12-18 12:59:30.912 INFO (MainThread) [ocpp] : send [2,"be70f900-de3d-4683-8f3e-4f4e145ddea7","GetConfiguration",{"key":["ClockAlignedDataInterval"]}]
2022-12-18 12:59:31.024 INFO (MainThread) [ocpp] : receive message [3,"be70f900-de3d-4683-8f3e-4f4e145ddea7",{"configurationKey":[{"key":"ClockAlignedDataInterval","readonly":true,"value":"0"}],"unknownKey":[]}]
2022-12-18 12:59:31.030 WARNING (MainThread) [custom_components.ocpp] ClockAlignedDataInterval is a read only setting
2022-12-18 12:59:31.036 INFO (MainThread) [ocpp] : send [2,"5be84183-1051-4e48-b58e-1110bd118841","GetConfiguration",{"key":["MeterValuesSampledData"]}]
2022-12-18 12:59:31.105 INFO (MainThread) [ocpp] : receive message [3,"5be84183-1051-4e48-b58e-1110bd118841",{"configurationKey":[{"key":"MeterValuesSampledData","readonly":true,"value":"true"}],"unknownKey":[]}]
2022-12-18 12:59:31.110 WARNING (MainThread) [custom_components.ocpp] MeterValuesSampledData is a read only setting
2022-12-18 12:59:31.128 INFO (MainThread) [ocpp] : send [2,"0490b01d-1a5f-4e46-9841-3fbfeb5d30d8","ChangeConfiguration",{"key":"ClockAlignedDataInterval","value":"900"}]
2022-12-18 12:59:31.277 INFO (MainThread) [ocpp] : receive message [3,"0490b01d-1a5f-4e46-9841-3fbfeb5d30d8",{"status":"Rejected"}]
2022-12-18 12:59:31.289 WARNING (MainThread) [custom_components.ocpp] Rejected while setting ClockAlignedDataInterval to 900
2022-12-18 12:59:31.299 INFO (MainThread) [ocpp] : send [2,"3cb9692c-ca3c-48cb-ad63-a7e2e1bf7ff6","ChangeConfiguration",{"key":"MeterValuesSampledData","value":"Energy.Active.Import.Register,Energy.Reactive.Import.Register,Energy.Active.Import.Interval,Energy.Reactive.Import.Interval,Power.Active.Import,Power.Reactive.Import,Power.Offered,Power.Factor,Current.Import,Current.Offered,Voltage,Frequency,SoC,Temperature"}]
2022-12-18 12:59:31.310 ERROR (MainThread) [custom_components.ocpp] Unexpected exception in connection to '': 'argument of type 'int' is not iterable'
Traceback (most recent call last):
  File "/config/custom_components/ocpp/api.py", line 920, in run
    await asyncio.gather(*self.tasks)
  File "/config/custom_components/ocpp/api.py", line 451, in post_connect
    if prof.SMART in self._attr_supported_features:
TypeError: argument of type 'int' is not iterable
2022-12-18 12:59:31.355 INFO (MainThread) [ocpp] : receive message [3,"3cb9692c-ca3c-48cb-ad63-a7e2e1bf7ff6",{"status":"Rejected"}]
2022-12-18 12:59:31.365 WARNING (MainThread) [custom_components.ocpp] Rejected while setting MeterValuesSampledData to Energy.Active.Import.Register,Energy.Reactive.Import.Register,Energy.Active.Import.Interval,Energy.Reactive.Import.Interval,Power.Active.Import,Power.Reactive.Import,Power.Offered,Power.Factor,Current.Import,Current.Offered,Voltage,Frequency,SoC,Temperature
2022-12-18 12:59:31.370 INFO (MainThread) [ocpp] : send [2,"3e13e34e-66e0-47cd-b550-d62996cb4a89","GetConfiguration",{"key":["MeterValueSampleInterval"]}]
2022-12-18 12:59:31.483 ERROR (MainThread) [homeassistant] Error doing job: Task exception was never retrieved
Traceback (most recent call last):
  File "/config/custom_components/ocpp/api.py", line 419, in post_connect
    await self.configure(
  File "/config/custom_components/ocpp/api.py", line 813, in configure
    resp = await self.call(req)
  File "/usr/local/lib/python3.10/site-packages/ocpp/charge_point.py", line 271, in call
    await self._send(call.to_json())
  File "/usr/local/lib/python3.10/site-packages/ocpp/charge_point.py", line 325, in _send
    await self._connection.send(message)
  File "/usr/local/lib/python3.10/site-packages/websockets/legacy/protocol.py", line 635, in send
    await self.ensure_open()
  File "/usr/local/lib/python3.10/site-packages/websockets/legacy/protocol.py", line 953, in ensure_open
    raise self.connection_closed_exc()
websockets.exceptions.ConnectionClosedOK: sent 1000 (OK); then received 1000 (OK)
2022-12-18 13:00:19.141 WARNING (MainThread) [homeassistant.components.camera] Updating xiaomi_cloud_map_extractor camera took longer than the scheduled update interval 0:00:05
2022-12-18 13:00:32.092 INFO (MainThread) [ocpp] : receive message [2,"19","BootNotification",{"chargePointVendor":"wallbe","chargePointModel":"Smart Charge Control","chargePointSerialNumber":"00000000596","firmwareVersion":"BF-01.04.13"}]
2022-12-18 13:00:32.101 INFO (MainThread) [ocpp] : send [3,"19",{"currentTime":"2022-12-18T13:00:32Z","interval":3600,"status":"Accepted"}]
2022-12-18 13:00:32.268 INFO (MainThread) [ocpp] : receive message [2,"20","StatusNotification",{"connectorId":0,"errorCode":"NoError","status":"Available","vendorErrorCode":"0","timestamp":"2022-12-18T13:00:32.002Z"}]
2022-12-18 13:00:32.272 INFO (MainThread) [ocpp] : send [3,"20",{}]
2022-12-18 13:00:32.392 INFO (MainThread) [ocpp] : receive message [2,"21","StatusNotification",{"connectorId":1,"errorCode":"NoError","status":"Preparing","vendorErrorCode":"0","timestamp":"2022-12-18T13:00:32.003Z"}]
2022-12-18 13:00:32.394 INFO (MainThread) [ocpp] : send [3,"21",{}]
2022-12-18 13:00:33.822 INFO (MainThread) [ocpp] : send [2,"535dd3e2-0c3a-44fd-a9e4-e002405667f2","GetConfiguration",{"key":["SupportedFeatureProfiles"]}]
2022-12-18 13:00:33.886 INFO (MainThread) [ocpp] : receive message [3,"535dd3e2-0c3a-44fd-a9e4-e002405667f2",{"configurationKey":[{"key":"SupportedFeatureProfiles","readonly":true,"value":"true"}],"unknownKey":[]}]
2022-12-18 13:00:33.891 WARNING (MainThread) [custom_components.ocpp] Unknown feature profile detected ignoring: true
2022-12-18 13:00:33.898 INFO (MainThread) [ocpp] : send [2,"830407a0-232d-49e7-beeb-3df9522b9a75","GetConfiguration",{"key":["NumberOfConnectors"]}]
2022-12-18 13:00:34.012 INFO (MainThread) [ocpp] : receive message [3,"830407a0-232d-49e7-beeb-3df9522b9a75",{"configurationKey":[{"key":"NumberOfConnectors","readonly":true,"value":"1"}],"unknownKey":[]}]
2022-12-18 13:00:34.019 INFO (MainThread) [ocpp] : send [2,"ff79c403-729f-4e83-b6b0-9ee79ba116e4","GetConfiguration",{"key":["HeartbeatInterval"]}]
2022-12-18 13:00:34.089 INFO (MainThread) [ocpp] : receive message [3,"ff79c403-729f-4e83-b6b0-9ee79ba116e4",{"configurationKey":[{"key":"HeartbeatInterval","readonly":false,"value":"3600"}],"unknownKey":[]}]
2022-12-18 13:00:34.096 INFO (MainThread) [ocpp] : send [2,"666f3a1f-77fb-4911-ba7b-00cfaa2e0515","GetConfiguration",{"key":["MeterValuesSampledData"]}]
2022-12-18 13:00:34.214 INFO (MainThread) [ocpp] : receive message [3,"666f3a1f-77fb-4911-ba7b-00cfaa2e0515",{"configurationKey":[{"key":"MeterValuesSampledData","readonly":true,"value":"true"}],"unknownKey":[]}]
2022-12-18 13:00:34.219 WARNING (MainThread) [custom_components.ocpp] MeterValuesSampledData is a read only setting
2022-12-18 13:00:34.226 INFO (MainThread) [ocpp] : send [2,"9f7dd331-8d7d-45df-a8c1-473ea5a4cd27","GetConfiguration",{"key":["SupportedFeatureProfiles"]}]
2022-12-18 13:00:34.340 INFO (MainThread) [ocpp] : receive message [3,"9f7dd331-8d7d-45df-a8c1-473ea5a4cd27",{"configurationKey":[{"key":"SupportedFeatureProfiles","readonly":true,"value":"true"}],"unknownKey":[]}]
2022-12-18 13:00:34.345 WARNING (MainThread) [custom_components.ocpp] Unknown feature profile detected ignoring: true
2022-12-18 13:00:34.352 INFO (MainThread) [ocpp] : send [2,"39a1dfba-a99f-4517-9fe9-6739505582d9","ChangeConfiguration",{"key":"MeterValuesSampledData","value":"Energy.Active.Import.Register,Energy.Reactive.Import.Register,Energy.Active.Import.Interval,Energy.Reactive.Import.Interval,Power.Active.Import,Power.Reactive.Import,Power.Offered,Power.Factor,Current.Import,Current.Offered,Voltage,Frequency,SoC,Temperature"}]
2022-12-18 13:00:34.420 INFO (MainThread) [ocpp] : receive message [3,"39a1dfba-a99f-4517-9fe9-6739505582d9",{"status":"Rejected"}]
2022-12-18 13:00:34.423 WARNING (MainThread) [custom_components.ocpp] Rejected while setting MeterValuesSampledData to Energy.Active.Import.Register,Energy.Reactive.Import.Register,Energy.Active.Import.Interval,Energy.Reactive.Import.Interval,Power.Active.Import,Power.Reactive.Import,Power.Offered,Power.Factor,Current.Import,Current.Offered,Voltage,Frequency,SoC,Temperature
2022-12-18 13:00:34.428 INFO (MainThread) [ocpp] : send [2,"97d93641-2e28-4eec-b348-bfb260e16035","GetConfiguration",{"key":["NumberOfConnectors"]}]
2022-12-18 13:00:34.545 INFO (MainThread) [ocpp] : receive message [3,"97d93641-2e28-4eec-b348-bfb260e16035",{"configurationKey":[{"key":"NumberOfConnectors","readonly":true,"value":"1"}],"unknownKey":[]}]
2022-12-18 13:00:34.553 INFO (MainThread) [ocpp] : send [2,"f57d0d48-4ae4-4224-a887-df7bdc8babf4","GetConfiguration",{"key":["MeterValueSampleInterval"]}]
2022-12-18 13:00:34.672 INFO (MainThread) [ocpp] : receive message [3,"f57d0d48-4ae4-4224-a887-df7bdc8babf4",{"configurationKey":[{"key":"MeterValueSampleInterval","readonly":false,"value":"60"}],"unknownKey":[]}]
2022-12-18 13:00:34.679 INFO (MainThread) [ocpp] : send [2,"475663ea-fae4-4e37-a6cd-64d5fd809e2e","GetConfiguration",{"key":["HeartbeatInterval"]}]
2022-12-18 13:00:34.748 INFO (MainThread) [ocpp] : receive message [3,"475663ea-fae4-4e37-a6cd-64d5fd809e2e",{"configurationKey":[{"key":"HeartbeatInterval","readonly":false,"value":"3600"}],"unknownKey":[]}]
2022-12-18 13:00:34.756 INFO (MainThread) [ocpp] : send [2,"42139e6a-3a32-437e-9547-e90bbf4e8297","GetConfiguration",{"key":["ClockAlignedDataInterval"]}]
2022-12-18 13:00:34.874 INFO (MainThread) [ocpp] : receive message [3,"42139e6a-3a32-437e-9547-e90bbf4e8297",{"configurationKey":[{"key":"ClockAlignedDataInterval","readonly":true,"value":"0"}],"unknownKey":[]}]
2022-12-18 13:00:34.879 WARNING (MainThread) [custom_components.ocpp] ClockAlignedDataInterval is a read only setting
2022-12-18 13:00:34.886 INFO (MainThread) [ocpp] : send [2,"edfc8665-7987-40e9-9392-754224eaa12e","GetConfiguration",{"key":["MeterValuesSampledData"]}]
2022-12-18 13:00:35.000 INFO (MainThread) [ocpp] : receive message [3,"edfc8665-7987-40e9-9392-754224eaa12e",{"configurationKey":[{"key":"MeterValuesSampledData","readonly":true,"value":"true"}],"unknownKey":[]}]
2022-12-18 13:00:35.004 WARNING (MainThread) [custom_components.ocpp] MeterValuesSampledData is a read only setting
2022-12-18 13:00:35.017 INFO (MainThread) [ocpp] : send [2,"16e5450f-1bfb-4017-8811-a90158165d61","ChangeConfiguration",{"key":"ClockAlignedDataInterval","value":"900"}]
2022-12-18 13:00:35.074 INFO (MainThread) [ocpp] : receive message [3,"16e5450f-1bfb-4017-8811-a90158165d61",{"status":"Rejected"}]
2022-12-18 13:00:35.075 WARNING (MainThread) [custom_components.ocpp] Rejected while setting ClockAlignedDataInterval to 900
2022-12-18 13:00:35.105 INFO (MainThread) [ocpp] : send [2,"08e11d44-2b95-48b5-8b25-f2d0288da05e","ChangeConfiguration",{"key":"MeterValuesSampledData","value":"Energy.Active.Import.Register,Energy.Reactive.Import.Register,Energy.Active.Import.Interval,Energy.Reactive.Import.Interval,Power.Active.Import,Power.Reactive.Import,Power.Offered,Power.Factor,Current.Import,Current.Offered,Voltage,Frequency,SoC,Temperature"}]
2022-12-18 13:00:35.115 ERROR (MainThread) [custom_components.ocpp] Unexpected exception in connection to '': 'argument of type 'int' is not iterable'
Traceback (most recent call last):
  File "/config/custom_components/ocpp/api.py", line 920, in run
    await asyncio.gather(*self.tasks)
  File "/config/custom_components/ocpp/api.py", line 451, in post_connect
    if prof.SMART in self._attr_supported_features:
TypeError: argument of type 'int' is not iterable
2022-12-18 13:00:35.217 INFO (MainThread) [ocpp] : receive message [3,"08e11d44-2b95-48b5-8b25-f2d0288da05e",{"status":"Rejected"}]
2022-12-18 13:00:35.239 WARNING (MainThread) [custom_components.ocpp] Rejected while setting MeterValuesSampledData to Energy.Active.Import.Register,Energy.Reactive.Import.Register,Energy.Active.Import.Interval,Energy.Reactive.Import.Interval,Power.Active.Import,Power.Reactive.Import,Power.Offered,Power.Factor,Current.Import,Current.Offered,Voltage,Frequency,SoC,Temperature
2022-12-18 13:00:35.276 INFO (MainThread) [ocpp] : send [2,"485407b6-566d-4b2e-8ead-bc53b31b07e2","GetConfiguration",{"key":["MeterValueSampleInterval"]}]
2022-12-18 13:00:35.358 ERROR (MainThread) [homeassistant] Error doing job: Task exception was never retrieved
Traceback (most recent call last):
  File "/config/custom_components/ocpp/api.py", line 419, in post_connect
    await self.configure(
  File "/config/custom_components/ocpp/api.py", line 813, in configure
    resp = await self.call(req)
  File "/usr/local/lib/python3.10/site-packages/ocpp/charge_point.py", line 271, in call
    await self._send(call.to_json())
  File "/usr/local/lib/python3.10/site-packages/ocpp/charge_point.py", line 325, in _send
    await self._connection.send(message)
  File "/usr/local/lib/python3.10/site-packages/websockets/legacy/protocol.py", line 635, in send
    await self.ensure_open()
  File "/usr/local/lib/python3.10/site-packages/websockets/legacy/protocol.py", line 953, in ensure_open
    raise self.connection_closed_exc()
websockets.exceptions.ConnectionClosedOK: sent 1000 (OK); then received 1000 (OK)

**Comment by drc38** [comment]
It looks like your charger is not ocpp compliant, read through thread #442 by way of example. You will need to go through and comment out the messages it does not support.

**Comment by linuxstony** [comment]
Alright - thank you for pointing me into the right direction. 

I also asked the vendor for a firmware upgrade and reported the problems with the OCPP interface - but i doubt, that they will be of much help because they even declined me any additional information about the backend at all - or even a password to access the web frontend (luckily the password was available somewhere on the internet)

I will debug alongsinde your mentioned thread and when I am finished write a guide what to do exactly for others to reproduce to get this one working. 

I appreciate your all time for looking into my problem.

**Comment by drc38** [comment]
You could also try adding `self._attr_supported_features |= prof.CORE` before line 511 in `api.py`

**Comment by linuxstony** [comment]
I removed the integration altogether and reinstalled it. I chose another version to install "main" and activated the options on the bottom.  

I activated the option to skip the OCPP-scheme-validation and to force the Smart-Charging-Profile. (Try and error)

Since then I got the Wallbox functioning without any hassle or reboot so far. 

I think with these options this box can be added to the supported devices just fine - when its desired I can summarize which options are available and which are not (e.g. SoC or Frequency are not returned as values so i removed them from the dashboard.

The slider for setting the Maximum Current is available and moveable - I wasn't yet able to confirm, that this is really set in the box though. Controlling the charging and the returning of values works like a charm. 

This issue (which wasn't really one) could therefore be closed. 

If you need me to collect some data for the inclusion into your documentation please tell me - I will do so immediately.

![ksnip_20221221-072216](https://user-images.githubusercontent.com/10862262/208835831-b285bed2-bd41-47ff-8e73-db996be3d84f.png)
![ksnip_20221221-071909](https://user-images.githubusercontent.com/10862262/208835837-9e4a7d8a-449b-4725-9c97-8b579969badd.png)
