### ISSUE TITLE
Unable to connect Wallbox CopperSB (TypeConstraintViolationError)

### ISSUE THREAD

**Issue by Wolf-Code** [lbbrhzn/ocpp#821]
## Version of the custom_component

v0.4.37

## Configuration

N/A

## Describe the bug
When enabling OCPP on my Wallbox CopperSB (according to the documentation) I get an update in Home Assistant containing actual values every couple of minutes, immediately after which all values are replaced by unavailable again.
As far as the charger is concerned, a connection was never established, and I get the following logs.
I've tried enabling and disabling the skipping of the verification and recreated the integration several times, with different charger names to be sure, but the result seems to stay the same.

## Debug log

```text

    Unexpected exception in connection to 'WallboxCopperSB': 'TypeConstraintViolationError: Payload for Action is syntactically correct but at least one of the fields violates data type constraints (e.g. “somestring”: 12), {'cause': "'Energy.Active.Import.Register,Energy.Reactive.Import.Register,Energy.Active.Import.Interval,Energy.Reactive.Import.Interval,Power.Active.Import,Power.Reactive.Import,Power.Offered,Power.Factor,Current.Import.L1,Current.Import.L2,Current.Import.L3,Current.Offered,Voltage.L1-N,Voltage.L2-N,Voltage.L3-N,Frequency,RPM,SoC,Temperature,Current.Export.L1,Current.Export.L2,Current.Export.L3,Energy.Active.Export.Register,Energy.Reactive.Export.Register,Energy.Active.Export.Interval,Energy.Reactive.Export.Interval,Power.Active.Export,Power.Reactive.Export' is too long", 'ocpp_message': <CallResult - unique_id=6a2a9edc-33dc-4af1-ab0d-e22145d5503b, action=GetConfiguration, payload={'unknownKey': [], 'configurationKey': [{'readonly': False, 'key': 'MeterValuesSampledData', 'value': 'Energy.Active.Import.Register,Energy.Reactive.Import.Register,Energy.Active.Import.Interval,Energy.Reactive.Import.Interval,Power.Active.Import,Power.Reactive.Import,Power.Offered,Power.Factor,Current.Import.L1,Current.Import.L2,Current.Import.L3,Current.Offered,Voltage.L1-N,Voltage.L2-N,Voltage.L3-N,Frequency,RPM,SoC,Temperature,Current.Export.L1,Current.Export.L2,Current.Export.L3,Energy.Active.Export.Register,Energy.Reactive.Export.Register,Energy.Active.Export.Interval,Energy.Reactive.Export.Interval,Power.Active.Export,Power.Reactive.Export'}]}>}'
    Unexpected exception in connection to 'WallboxCopperSB': 'TypeConstraintViolationError: Payload for Action is syntactically correct but at least one of the fields violates data type constraints (e.g. “somestring”: 12), {'cause': "'Energy.Active.Import.Register,Energy.Reactive.Import.Register,Energy.Active.Import.Interval,Energy.Reactive.Import.Interval,Power.Active.Import,Power.Reactive.Import,Power.Offered,Power.Factor,Current.Import.L1,Current.Import.L2,Current.Import.L3,Current.Offered,Voltage.L1-N,Voltage.L2-N,Voltage.L3-N,Frequency,RPM,SoC,Temperature,Current.Export.L1,Current.Export.L2,Current.Export.L3,Energy.Active.Export.Register,Energy.Reactive.Export.Register,Energy.Active.Export.Interval,Energy.Reactive.Export.Interval,Power.Active.Export,Power.Reactive.Export' is too long", 'ocpp_message': <CallResult - unique_id=f36b4e06-253f-4820-b9e1-3ca23237d476, action=GetConfiguration, payload={'unknownKey': [], 'configurationKey': [{'readonly': False, 'key': 'MeterValuesSampledData', 'value': 'Energy.Active.Import.Register,Energy.Reactive.Import.Register,Energy.Active.Import.Interval,Energy.Reactive.Import.Interval,Power.Active.Import,Power.Reactive.Import,Power.Offered,Power.Factor,Current.Import.L1,Current.Import.L2,Current.Import.L3,Current.Offered,Voltage.L1-N,Voltage.L2-N,Voltage.L3-N,Frequency,RPM,SoC,Temperature,Current.Export.L1,Current.Export.L2,Current.Export.L3,Energy.Active.Export.Register,Energy.Reactive.Export.Register,Energy.Active.Export.Interval,Energy.Reactive.Export.Interval,Power.Active.Export,Power.Reactive.Export'}]}>}'
    Unexpected exception in connection to 'WallboxCopperSB': 'TypeConstraintViolationError: Payload for Action is syntactically correct but at least one of the fields violates data type constraints (e.g. “somestring”: 12), {'cause': "'Energy.Active.Import.Register,Energy.Reactive.Import.Register,Energy.Active.Import.Interval,Energy.Reactive.Import.Interval,Power.Active.Import,Power.Reactive.Import,Power.Offered,Power.Factor,Current.Import.L1,Current.Import.L2,Current.Import.L3,Current.Offered,Voltage.L1-N,Voltage.L2-N,Voltage.L3-N,Frequency,RPM,SoC,Temperature,Current.Export.L1,Current.Export.L2,Current.Export.L3,Energy.Active.Export.Register,Energy.Reactive.Export.Register,Energy.Active.Export.Interval,Energy.Reactive.Export.Interval,Power.Active.Export,Power.Reactive.Export' is too long", 'ocpp_message': <CallResult - unique_id=ed486797-3c01-40db-85c7-e6a9fa613cd1, action=GetConfiguration, payload={'unknownKey': [], 'configurationKey': [{'readonly': False, 'key': 'MeterValuesSampledData', 'value': 'Energy.Active.Import.Register,Energy.Reactive.Import.Register,Energy.Active.Import.Interval,Energy.Reactive.Import.Interval,Power.Active.Import,Power.Reactive.Import,Power.Offered,Power.Factor,Current.Import.L1,Current.Import.L2,Current.Import.L3,Current.Offered,Voltage.L1-N,Voltage.L2-N,Voltage.L3-N,Frequency,RPM,SoC,Temperature,Current.Export.L1,Current.Export.L2,Current.Export.L3,Energy.Active.Export.Register,Energy.Reactive.Export.Register,Energy.Active.Export.Interval,Energy.Reactive.Export.Interval,Power.Active.Export,Power.Reactive.Export'}]}>}'
    Unexpected exception in connection to 'WallboxCopperSB': 'TypeConstraintViolationError: Payload for Action is syntactically correct but at least one of the fields violates data type constraints (e.g. “somestring”: 12), {'cause': "'Energy.Active.Import.Register,Energy.Reactive.Import.Register,Energy.Active.Import.Interval,Energy.Reactive.Import.Interval,Power.Active.Import,Power.Reactive.Import,Power.Offered,Power.Factor,Current.Import.L1,Current.Import.L2,Current.Import.L3,Current.Offered,Voltage.L1-N,Voltage.L2-N,Voltage.L3-N,Frequency,RPM,SoC,Temperature,Current.Export.L1,Current.Export.L2,Current.Export.L3,Energy.Active.Export.Register,Energy.Reactive.Export.Register,Energy.Active.Export.Interval,Energy.Reactive.Export.Interval,Power.Active.Export,Power.Reactive.Export' is too long", 'ocpp_message': <CallResult - unique_id=f06e0c55-4a6e-4f0a-9929-581b3eceed35, action=GetConfiguration, payload={'unknownKey': [], 'configurationKey': [{'readonly': False, 'key': 'MeterValuesSampledData', 'value': 'Energy.Active.Import.Register,Energy.Reactive.Import.Register,Energy.Active.Import.Interval,Energy.Reactive.Import.Interval,Power.Active.Import,Power.Reactive.Import,Power.Offered,Power.Factor,Current.Import.L1,Current.Import.L2,Current.Import.L3,Current.Offered,Voltage.L1-N,Voltage.L2-N,Voltage.L3-N,Frequency,RPM,SoC,Temperature,Current.Export.L1,Current.Export.L2,Current.Export.L3,Energy.Active.Export.Register,Energy.Reactive.Export.Register,Energy.Active.Export.Interval,Energy.Reactive.Export.Interval,Power.Active.Export,Power.Reactive.Export'}]}>}'
    Unexpected exception in connection to 'WallboxCopperSB': 'TypeConstraintViolationError: Payload for Action is syntactically correct but at least one of the fields violates data type constraints (e.g. “somestring”: 12), {'cause': "'Energy.Active.Import.Register,Energy.Reactive.Import.Register,Energy.Active.Import.Interval,Energy.Reactive.Import.Interval,Power.Active.Import,Power.Reactive.Import,Power.Offered,Power.Factor,Current.Import.L1,Current.Import.L2,Current.Import.L3,Current.Offered,Voltage.L1-N,Voltage.L2-N,Voltage.L3-N,Frequency,RPM,SoC,Temperature,Current.Export.L1,Current.Export.L2,Current.Export.L3,Energy.Active.Export.Register,Energy.Reactive.Export.Register,Energy.Active.Export.Interval,Energy.Reactive.Export.Interval,Power.Active.Export,Power.Reactive.Export' is too long", 'ocpp_message': <CallResult - unique_id=5826712d-79a5-4738-ac39-f7e9ab8e3b12, action=GetConfiguration, payload={'unknownKey': [], 'configurationKey': [{'readonly': False, 'key': 'MeterValuesSampledData', 'value': 'Energy.Active.Import.Register,Energy.Reactive.Import.Register,Energy.Active.Import.Interval,Energy.Reactive.Import.Interval,Power.Active.Import,Power.Reactive.Import,Power.Offered,Power.Factor,Current.Import.L1,Current.Import.L2,Current.Import.L3,Current.Offered,Voltage.L1-N,Voltage.L2-N,Voltage.L3-N,Frequency,RPM,SoC,Temperature,Current.Export.L1,Current.Export.L2,Current.Export.L3,Energy.Active.Export.Register,Energy.Reactive.Export.Register,Energy.Active.Export.Interval,Energy.Reactive.Export.Interval,Power.Active.Export,Power.Reactive.Export'}]}>}'

Traceback (most recent call last):
  File "/usr/local/lib/python3.10/site-packages/ocpp/messages.py", line 227, in validate_payload
    validator.validate(message.payload)
  File "/usr/local/lib/python3.10/site-packages/jsonschema/validators.py", line 314, in validate
    raise error
jsonschema.exceptions.ValidationError: 'Energy.Active.Import.Register,Energy.Reactive.Import.Register,Energy.Active.Import.Interval,Energy.Reactive.Import.Interval,Power.Active.Import,Power.Reactive.Import,Power.Offered,Power.Factor,Current.Import.L1,Current.Import.L2,Current.Import.L3,Current.Offered,Voltage.L1-N,Voltage.L2-N,Voltage.L3-N,Frequency,RPM,SoC,Temperature,Current.Export.L1,Current.Export.L2,Current.Export.L3,Energy.Active.Export.Register,Energy.Reactive.Export.Register,Energy.Active.Export.Interval,Energy.Reactive.Export.Interval,Power.Active.Export,Power.Reactive.Export' is too long

Failed validating 'maxLength' in schema['properties']['configurationKey']['items']['properties']['value']:
    {'maxLength': 500, 'type': 'string'}

On instance['configurationKey'][0]['value']:
    'Energy.Active.Import.Register,Energy.Reactive.Import.Register,Energy.Active.Import.Interval,Energy.Reactive.Import.Interval,Power.Active.Import,Power.Reactive.Import,Power.Offered,Power.Factor,Current.Import.L1,Current.Import.L2,Current.Import.L3,Current.Offered,Voltage.L1-N,Voltage.L2-N,Voltage.L3-N,Frequency,RPM,SoC,Temperature,Current.Export.L1,Current.Export.L2,Current.Export.L3,Energy.Active.Export.Register,Energy.Reactive.Export.Register,Energy.Active.Export.Interval,Energy.Reactive.Export.Interval,Power.Active.Export,Power.Reactive.Export'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/config/custom_components/ocpp/api.py", line 920, in run
    await asyncio.gather(*self.tasks)
  File "/config/custom_components/ocpp/api.py", line 415, in post_connect
    await self.configure(
  File "/config/custom_components/ocpp/api.py", line 813, in configure
    resp = await self.call(req)
  File "/usr/local/lib/python3.10/site-packages/ocpp/charge_point.py", line 293, in call
    validate_payload(response, self._ocpp_version)
  File "/usr/local/lib/python3.10/site-packages/ocpp/messages.py", line 240, in validate_payload
    raise TypeConstraintViolationError(
ocpp.exceptions.TypeConstraintViolationError: TypeConstraintViolationError: Payload for Action is syntactically correct but at least one of the fields violates data type constraints (e.g. “somestring”: 12), {'cause': "'Energy.Active.Import.Register,Energy.Reactive.Import.Register,Energy.Active.Import.Interval,Energy.Reactive.Import.Interval,Power.Active.Import,Power.Reactive.Import,Power.Offered,Power.Factor,Current.Import.L1,Current.Import.L2,Current.Import.L3,Current.Offered,Voltage.L1-N,Voltage.L2-N,Voltage.L3-N,Frequency,RPM,SoC,Temperature,Current.Export.L1,Current.Export.L2,Current.Export.L3,Energy.Active.Export.Register,Energy.Reactive.Export.Register,Energy.Active.Export.Interval,Energy.Reactive.Export.Interval,Power.Active.Export,Power.Reactive.Export' is too long", 'ocpp_message': <CallResult - unique_id=b040565a-33df-4eda-b401-44d83d8a3d0e, action=GetConfiguration, payload={'unknownKey': [], 'configurationKey': [{'readonly': False, 'key': 'MeterValuesSampledData', 'value': 'Energy.Active.Import.Register,Energy.Reactive.Import.Register,Energy.Active.Import.Interval,Energy.Reactive.Import.Interval,Power.Active.Import,Power.Reactive.Import,Power.Offered,Power.Factor,Current.Import.L1,Current.Import.L2,Current.Import.L3,Current.Offered,Voltage.L1-N,Voltage.L2-N,Voltage.L3-N,Frequency,RPM,SoC,Temperature,Current.Export.L1,Current.Export.L2,Current.Export.L3,Energy.Active.Export.Register,Energy.Reactive.Export.Register,Energy.Active.Export.Interval,Energy.Reactive.Export.Interval,Power.Active.Export,Power.Reactive.Export'}]}>}


```

**Comment by drc38** [comment]
Others using the Pulsar have had a similar issue, search issues and discussion for the solution
